=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Schemas/Amplitude.Unity.Simulation.SimulationDescriptor.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Datatable" />
  <xs:element name="SimulationDescriptor" nillable="true" type="SimulationDescriptor" />
  <xs:complexType name="SimulationDescriptor">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="1" name="ProportionalProperty" type="SimulationPropertyDescriptor_Proportional" />
        <xs:element minOccurs="0" maxOccurs="1" name="Property" type="SimulationPropertyDescriptor" />
      </xs:choice>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="1" name="CountModifier" type="CountSimulationModifierDescriptor" />
        <xs:element minOccurs="0" maxOccurs="1" name="BinaryModifier" type="BinarySimulationModifierDescriptor" />
        <xs:element minOccurs="0" maxOccurs="1" name="Modifier" type="SingleSimulationModifierDescriptor" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute default="true" name="IsSerializable" type="xs:boolean" />
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="Type" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="SimulationPropertyDescriptor_Proportional">
    <xs:complexContent mixed="false">
      <xs:extension base="SimulationPropertyDescriptor">
        <xs:attribute name="Maximum" type="xs:string" />
        <xs:attribute name="Minimum" type="xs:string" />
        <xs:attribute name="StartingRatio" type="xs:float" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SimulationPropertyDescriptor">
    <xs:attribute default="0" name="BaseValue" type="xs:float" />
    <xs:attribute default="None" name="Composition" type="SimulationPropertyComposition" />
    <xs:attribute default="None" name="RoundingFunction" type="SimulationPropertyRoundingFunction" />
    <xs:attribute default="false" name="IsSealed" type="xs:boolean" />
    <xs:attribute default="false" name="IsSerializable" type="xs:boolean" />
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="MaxValue" type="xs:string" />
    <xs:attribute name="MinValue" type="xs:string" />
  </xs:complexType>
  <xs:simpleType name="SimulationPropertyComposition">
    <xs:restriction base="xs:string">
      <xs:enumeration value="None" />
      <xs:enumeration value="Maximum" />
      <xs:enumeration value="Minimum" />
      <xs:enumeration value="Sum" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="SimulationPropertyRoundingFunction">
    <xs:restriction base="xs:string">
      <xs:enumeration value="None" />
      <xs:enumeration value="Ceil" />
      <xs:enumeration value="Floor" />
      <xs:enumeration value="Round" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="CountSimulationModifierDescriptor">
    <xs:complexContent mixed="false">
      <xs:extension base="SimulationModifierDescriptor">
        <xs:attribute default="1" name="Multiplier" type="xs:string" />
        <xs:attribute name="CountPath" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SimulationModifierDescriptor">
    <xs:attribute default="false" name="SearchValueFromPath" type="xs:boolean" />
    <xs:attribute name="Operation" type="ModifierOperation" use="required" />
    <xs:attribute default="0" name="Priority" type="xs:float" />
    <xs:attribute default="" name="TooltipOverride" type="xs:string" />
    <xs:attribute default="false" name="TooltipHidden" type="xs:boolean" />
    <xs:attribute default="false" name="TooltipHiddenIfPathInvalid" type="xs:boolean" />
    <xs:attribute default="false" name="EnforceContext" type="xs:boolean" />
    <xs:attribute default="false" name="ValueMustBePositive" type="xs:boolean" />
    <xs:attribute default="false" name="UseIfInsteadOfWhere" type="xs:boolean" />
    <xs:attribute default="false" name="ForceFrom" type="xs:boolean" />
    <xs:attribute name="Path" type="xs:string" />
    <xs:attribute name="TargetProperty" type="xs:string" />
  </xs:complexType>
  <xs:simpleType name="ModifierOperation">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Force" />
      <xs:enumeration value="Addition" />
      <xs:enumeration value="Subtraction" />
      <xs:enumeration value="Multiplication" />
      <xs:enumeration value="Division" />
      <xs:enumeration value="Power" />
      <xs:enumeration value="Percent" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="BinarySimulationModifierDescriptor">
    <xs:complexContent mixed="false">
      <xs:extension base="SimulationModifierDescriptor">
        <xs:attribute name="BinaryOperation" type="ModifierOperation" use="required" />
        <xs:attribute name="Left" type="xs:string" />
        <xs:attribute name="Right" type="xs:string" />
        <xs:attribute default="false" name="EnforceRightAsPer" type="xs:boolean" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SingleSimulationModifierDescriptor">
    <xs:complexContent mixed="false">
      <xs:extension base="SimulationModifierDescriptor">
        <xs:attribute name="Value" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>

=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Simulation/SimulationDescriptors[EmpireImprovements_DLC2].xml
<?xml version="1.0" encoding="utf-8"?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Schemas/Amplitude.Unity.Simulation.SimulationDescriptor.xsd">


    <!-- ########################### -->
    <!-- ######  Juggernauts  ###### -->
    <!-- ########################### -->

    <SimulationDescriptor Name="EmpireImprovementMovement01Juggernaut" Type="EmpireImprovement">
        <Modifier TargetProperty="MaximumMovement" Operation="Addition" Value="3" Path="ClassEmpire//ClassGarrison/ClassShip,ShipRoleJuggernaut"/>
    </SimulationDescriptor>
    <SimulationDescriptor Name="EmpireImprovementMovement01JuggernautMajorHisshos" Type="EmpireImprovement">
        <Modifier TargetProperty="MaximumMovement" Operation="Addition" Value="6" Path="ClassEmpire//ClassGarrison/ClassShip,ShipRoleJuggernaut"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="EmpireImprovementSlotsMilitary1Juggernaut" Type="EmpireImprovement">
        <Modifier TargetProperty="ShipHealth"       Operation="Addition"        Value="28000"    Path="ClassEmpire/ClassGarrison/ClassShip,ShipRoleJuggernaut/ClassSection,ClassSectionCoreJuggernaut" TooltipOverride="%EmpireImprovementImprovedHullJuggernautHealthOverride"/>
        <Modifier TargetProperty="ShipHealth"       Operation="Addition"        Value="28000"   Path="ClassEmpire/ClassStarSystem/ClassGarrison/ClassShip,ShipRoleJuggernaut/ClassSection,ClassSectionCoreJuggernaut" TooltipHidden="true"/>
    </SimulationDescriptor>
    
    <SimulationDescriptor Name="EmpireImprovementImprovedHull1Juggernaut" Type="EmpireImprovement" >
        <Modifier TargetProperty="JuggernautModuleCostMultiplier"   Operation="Addition"    Value="2"       Path="ClassEmpire" Priority="0" TooltipHidden="true"/>
        
        <Modifier TargetProperty="Multiplier"                       Operation="Addition"    Value="2"       Path="ClassEmpire/ClassGarrison/ClassShip,ShipRoleJuggernaut/ClassSection/ClassModule" Priority="0"     TooltipOverride="%EmpireImprovementImprovedHullJuggernautOverride"/>
        <Modifier TargetProperty="ShipHealth"                       Operation="Addition"    Value="14000"   Path="ClassEmpire/ClassGarrison/ClassShip,ShipRoleJuggernaut/ClassSection,ClassSectionCoreJuggernaut"   TooltipOverride="%EmpireImprovementImprovedHullJuggernautHealthOverride"/>
        
        <Modifier TargetProperty="Multiplier"                       Operation="Addition"    Value="2"       Path="ClassEmpire/ClassStarSystem/ClassGarrison/ClassShip,ShipRoleJuggernaut/ClassSection/ClassModule" Priority="0" TooltipHidden="true"/>
        <Modifier TargetProperty="ShipHealth"                       Operation="Addition"    Value="14000"   Path="ClassEmpire/ClassStarSystem/ClassGarrison/ClassShip,ShipRoleJuggernaut/ClassSection,ClassSectionCoreJuggernaut" TooltipHidden="true"/>
         
        <Modifier TargetProperty="JuggernautMultiplier"             Operation="Addition"    Value="2"       Path="ClassEmpire/ClassStarSystem" Priority="0" TooltipHidden="true"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="EmpireImprovementImprovedHull4Juggernaut" Type="EmpireImprovement" >
        <Modifier TargetProperty="JuggernautModuleCostMultiplier"   Operation="Addition"    Value="2"       Path="ClassEmpire" Priority="1" TooltipHidden="true"/>
        
        <Modifier TargetProperty="Multiplier"                       Operation="Addition"    Value="2"       Path="ClassEmpire/ClassGarrison/ClassShip,ShipRoleJuggernaut/ClassSection/ClassModule" Priority="1"     TooltipOverride="%EmpireImprovementImprovedHullJuggernautOverride"/>
        <Modifier TargetProperty="ShipHealth"                       Operation="Addition"    Value="14000"    Path="ClassEmpire/ClassGarrison/ClassShip,ShipRoleJuggernaut/ClassSection,ClassSectionCoreJuggernaut"   TooltipOverride="%EmpireImprovementImprovedHullJuggernautHealthOverride"/>
        
        <Modifier TargetProperty="Multiplier"                       Operation="Addition"    Value="2"       Path="ClassEmpire/ClassStarSystem/ClassGarrison/ClassShip,ShipRoleJuggernaut/ClassSection/ClassModule" Priority="1" TooltipHidden="true"/>
        <Modifier TargetProperty="ShipHealth"                       Operation="Addition"    Value="14000"    Path="ClassEmpire/ClassStarSystem/ClassGarrison/ClassShip,ShipRoleJuggernaut/ClassSection,ClassSectionCoreJuggernaut" TooltipHidden="true"/>

        <Modifier TargetProperty="JuggernautMultiplier"             Operation="Addition"    Value="2"       Path="ClassEmpire/ClassStarSystem" Priority="0" TooltipHidden="true"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="EmpireImprovementImprovedHull5Juggernaut" Type="EmpireImprovement" >
        <Modifier TargetProperty="JuggernautModuleCostMultiplier"   Operation="Addition"       Value="3"       Path="ClassEmpire" Priority="2" TooltipHidden="true"/>
        
        <Modifier TargetProperty="Multiplier"                       Operation="Addition"       Value="3"       Path="ClassEmpire/ClassGarrison/ClassShip,ShipRoleJuggernaut/ClassSection/ClassModule" Priority="2"     TooltipOverride="%EmpireImprovementImprovedHullJuggernautOverride"/>
        <Modifier TargetProperty="ShipHealth"                       Operation="Addition"    Value="14000"    Path="ClassEmpire/ClassGarrison/ClassShip,ShipRoleJuggernaut/ClassSection,ClassSectionCoreJuggernaut"   TooltipOverride="%EmpireImprovementImprovedHullJuggernautHealthOverride"/>
        
        <Modifier TargetProperty="Multiplier"                       Operation="Addition"       Value="3"       Path="ClassEmpire/ClassStarSystem/ClassGarrison/ClassShip,ShipRoleJuggernaut/ClassSection/ClassModule" Priority="2" TooltipHidden="true"/>
        <Modifier TargetProperty="ShipHealth"                       Operation="Addition"    Value="14000"    Path="ClassEmpire/ClassStarSystem/ClassGarrison/ClassShip,ShipRoleJuggernaut/ClassSection,ClassSectionCoreJuggernaut" TooltipHidden="true"/>

        <Modifier TargetProperty="JuggernautMultiplier"             Operation="Addition"    Value="3"       Path="ClassEmpire/ClassStarSystem" Priority="0" TooltipHidden="true"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="EmpireImprovementImprovedHull6Juggernaut" Type="EmpireImprovement" >
        <Modifier TargetProperty="JuggernautModuleCostMultiplier"   Operation="Addition"    Value="2"       Path="ClassEmpire" Priority="3" TooltipHidden="true"/>
        
        <Modifier TargetProperty="Multiplier"                       Operation="Addition"    Value="2"       Path="ClassEmpire/ClassGarrison/ClassShip,ShipRoleJuggernaut/ClassSection/ClassModule" Priority="3"     TooltipOverride="%EmpireImprovementImprovedHullJuggernautOverride"/>
        <Modifier TargetProperty="ShipHealth"                       Operation="Addition"    Value="28000"   Path="ClassEmpire/ClassGarrison/ClassShip,ShipRoleJuggernaut/ClassSection,ClassSectionCoreJuggernaut"   TooltipOverride="%EmpireImprovementImprovedHullJuggernautHealthOverride"/>
        
        <Modifier TargetProperty="Multiplier"                       Operation="Force"       Value="2"       Path="ClassEmpire/ClassStarSystem/ClassGarrison/ClassShip,ShipRoleJuggernaut/ClassSection/ClassModule" Priority="3" TooltipHidden="true"/>
        <Modifier TargetProperty="ShipHealth"                       Operation="Addition"    Value="28000"   Path="ClassEmpire/ClassStarSystem/ClassGarrison/ClassShip,ShipRoleJuggernaut/ClassSection,ClassSectionCoreJuggernaut" TooltipHidden="true"/>

        <Modifier TargetProperty="JuggernautMultiplier"             Operation="Addition"    Value="2"       Path="ClassEmpire/ClassStarSystem" Priority="0" TooltipHidden="true"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="EmpireImprovementDiplomacyBonus1MajorHissho" Type="EmpireImprovement">
        <Modifier TargetProperty="MinorFactionsGameplayUnlocked" Operation="Addition" Value="1" Path="ClassEmpire" TooltipHidden="true"/>
    </SimulationDescriptor>

    <!--##################-->
    <!--## HISSHO QUEST ##-->
    <!--##################-->

    <SimulationDescriptor Name="EmpireImprovementQuestHisshos05"      Type="EmpireImprovement"/>
    <SimulationDescriptor Name="EmpireImprovementQuestHisshos06"      Type="EmpireImprovement"/>
    
    <SimulationDescriptor Name="EmpireImprovementQuestHisshos07"      Type="EmpireImprovement">
        <Modifier TargetProperty="ShipDamage"       Operation="Addition"           Value="0.15"       Path="ClassEmpire,ObedienceStatusEmpire3/ClassGarrisonFleet" UseIfInsteadOfWhere="true"/>
        <Modifier TargetProperty="ShipDamage"       Operation="Addition"           Value="0.3"       Path="ClassEmpire,ObedienceStatusEmpire4/ClassGarrisonFleet" UseIfInsteadOfWhere="true"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="EmpireImprovementQuestHisshos08"      Type="EmpireImprovement">
        <Modifier TargetProperty="BoostToHonorInShipBattle"         Operation="Addition"           Value="0.5"       Path="ClassEmpire" TooltipHidden="true"/>
        <Modifier TargetProperty="BoostToHonorInShipBattle"         Operation="Percent"            Value="0.5"       Path="ClassEmpire/ClassGarrisonFleet"/>
        <Modifier TargetProperty="BoostToHonorInGroundBattle"       Operation="Addition"           Value="0.5"       Path="ClassEmpire" TooltipHidden="true"/>
        <Modifier TargetProperty="BoostToHonorInGroundBattle"       Operation="Percent"            Value="0.5"       Path="ClassEmpire/ClassStarSystem"/>
    </SimulationDescriptor>

</Datatable>

=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Simulation/SimulationDescriptors[GameSpeed].xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Schemas/Amplitude.Unity.Simulation.SimulationDescriptor.xsd">

    <!-- Game speed -->
    <SimulationDescriptor Name="GameSpeedFast" Type="GameSpeed">
        <Modifier TargetProperty="GameSpeedTrendMultiplier"             Operation="Force"           Value="1"/> <!-- modded -->
        <Modifier TargetProperty="GameSpeedMultiplier"                  Operation="Force"           Value=".5"/>
        <Modifier TargetProperty="GameSpeedProductionCostReduction"     Operation="Addition"        Value="0.5"         Priority="-2"   Path="ClassEmpire"/>
        <Modifier TargetProperty="GameSpeedProductionCostReduction"     Operation="Addition"        Value="0.5"         Priority="-2"   Path="ClassEmpire/ClassStarSystem"/>
        <Modifier TargetProperty="EconomicVictoryDustAmountRequired"    Operation="Multiplication"  Value="0.75"        Priority="-2"   Path="ClassEmpire"/>
        <Modifier TargetProperty="GameSpeedPirateTrendMultiplier"       Operation="Force"           Value="1.25"        Priority="-2"   Path="ClassEmpire"/>
        <Modifier TargetProperty="BaseTurnsBeforeFleetSpawn"            Operation="Multiplication"  Value="0.8"                         Path="ClassEmpire"/>
        <Modifier TargetProperty="LastTurn"                             Operation="Multiplication"  Value="0.5"                         Path="ClassEmpire"/>
        <Modifier TargetProperty="NetMinorEmpireMoney"                  Operation="Multiplication"  Value="1.5"         Priority="2"    Path="ClassEmpire,EmpireTypeMinor"/>
        <Modifier TargetProperty="GameSpeedScienceDiplomacy"       Operation="Force"               Value="0.5"        Priority="-2"   Path="ClassEmpire/ClassDiplomacy/ClassDiplomaticEmpire,DiplomaticAbilityEffectScienceAgreement"/>
        <Modifier TargetProperty="FactionPactDuration"                  Operation="Multiplication"  Value="0.5"         Priority="-2"   Path="ClassEmpire/ClassDiplomacy/ClassDiplomaticEmpire,FactionPact"/>
        <Modifier TargetProperty="HealthRegenerationRatio"              Operation="Multiplication"  Value="1.5"                         Path="ClassEmpire/ClassGarrison/ClassShip" Priority="10" />
        <Modifier TargetProperty="GameSpeedHackMultiplier"              Operation="Force"           Value="1.25"                        Path="ClassEmpire"/>
        <Modifier TargetProperty="GameSpeedMinorPirateHackingStartMultiplier"                  Operation="Force"           Value=".5"/>
        <Modifier TargetProperty="PressureTrend"                        Operation="Multiplication"  Value="$(GameSpeedTrendMultiplier)" Path="ClassEmpire/ClassDiplomacy/ClassDiplomaticEmpire"/>
    </SimulationDescriptor>

</Datatable>

=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Simulation/SimulationDescriptors[Anomaly_DLC2].xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Schemas/Amplitude.Unity.Simulation.SimulationDescriptor.xsd">

    <SimulationDescriptor Name="PlanetAnomalyRemainsEncounterLarge" Type="PlanetAnomaly">
        <Modifier TargetProperty="PlanetRawDust"    Value="5" Operation="Subtraction" Path="ClassPlanet"/>
        <Modifier TargetProperty="PlanetRawScience" Value="5" Operation="Addition" Path="ClassPlanet"/>
    </SimulationDescriptor>
    <SimulationDescriptor Name="PlanetAnomalyRemainsEncounterMedium" Type="PlanetAnomaly">
        <Modifier TargetProperty="PlanetRawDust"    Value="3" Operation="Subtraction" Path="ClassPlanet"/>
        <Modifier TargetProperty="PlanetRawScience" Value="3" Operation="Addition" Path="ClassPlanet"/>
    </SimulationDescriptor>
    <SimulationDescriptor Name="PlanetAnomalyRemainsEncounterSmall" Type="PlanetAnomaly">
        <Modifier TargetProperty="PlanetRawDust"    Value="1" Operation="Subtraction" Path="ClassPlanet"/>
        <Modifier TargetProperty="PlanetRawScience" Value="1" Operation="Addition" Path="ClassPlanet"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="PlanetAnomalyRemainsMinorFaction" Type="PlanetAnomaly">
        <Modifier           TargetProperty="PlanetRawDust"      Operation="Addition" Value="1"   Path="ClassPlanet"/>
        <Modifier           TargetProperty="PlanetRawScience"   Operation="Addition" Value="1"   Path="ClassPlanet"/>
        <BinaryModifier     TargetProperty="Happiness"          Operation="Addition" Left="1" BinaryOperation="Multiplication" Right="$(Population)"      />
        <Modifier           TargetProperty="HappinessRaw"       Operation="Addition" Value="1" TooltipHidden="true" />
    </SimulationDescriptor>

    <SimulationDescriptor Name="PlanetAnomalyRemainsPirateLairLarge" Type="PlanetAnomaly">
        <Modifier   TargetProperty="PlanetRawDust"      Operation="Addition" Value="5"   Path="ClassPlanet"/>
        <Modifier   TargetProperty="PlanetRawIndustry"  Operation="Addition" Value="5"   Path="ClassPlanet"/>
    </SimulationDescriptor>
    <SimulationDescriptor Name="PlanetAnomalyRemainsPirateLairMedium" Type="PlanetAnomaly">
        <Modifier   TargetProperty="PlanetRawDust"      Operation="Addition" Value="3"   Path="ClassPlanet"/>
        <Modifier   TargetProperty="PlanetRawIndustry"  Operation="Addition" Value="3"   Path="ClassPlanet"/>
    </SimulationDescriptor>
    <SimulationDescriptor Name="PlanetAnomalyRemainsPirateLairSmall" Type="PlanetAnomaly">
        <Modifier   TargetProperty="PlanetRawDust"      Operation="Addition" Value="1"   Path="ClassPlanet"/>
        <Modifier   TargetProperty="PlanetRawIndustry"  Operation="Addition" Value="1"   Path="ClassPlanet"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="PlanetAnomalyRemainsGroundBattleLarge" Type="PlanetAnomaly">
        <Modifier TargetProperty="PlanetRawFood"    Value="5" Operation="Subtraction" Path="ClassPlanet"/>
        <Modifier TargetProperty="PlanetRawScience" Value="5" Operation="Addition" Path="ClassPlanet"/>
    </SimulationDescriptor>
    <SimulationDescriptor Name="PlanetAnomalyRemainsGroundBattleMedium" Type="PlanetAnomaly">
        <Modifier TargetProperty="PlanetRawFood"    Value="3" Operation="Subtraction" Path="ClassPlanet"/>
        <Modifier TargetProperty="PlanetRawScience" Value="3" Operation="Addition" Path="ClassPlanet"/>
    </SimulationDescriptor>
    <SimulationDescriptor Name="PlanetAnomalyRemainsGroundBattleSmall" Type="PlanetAnomaly">
        <Modifier TargetProperty="PlanetRawFood"    Value="1" Operation="Subtraction" Path="ClassPlanet"/>
        <Modifier TargetProperty="PlanetRawScience" Value="1" Operation="Addition" Path="ClassPlanet"/>
    </SimulationDescriptor>
</Datatable>

=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Simulation/Battles/SimulationDescriptors[Encounter].xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../../Schemas/Amplitude.Unity.Simulation.SimulationDescriptor.xsd">
    <SimulationDescriptor Name="ClassModuleSupportEncounter" Type="ClassModuleSupport">

        <Modifier TargetProperty="DamageIncreasePercent"   Operation="Addition"    Value="$(DamageIncreasePercent)"   Path="../ClassFlotilla/ClassShipEncounter"       Priority="1"/>

        <Modifier TargetProperty="MaximumShield"            Operation="Addition" Value="$(FlotillaMaximumShield)"       Path="../ClassFlotilla"     Priority="1"/>
        <Modifier TargetProperty="ShieldAbsorption"         Operation="Addition" Value="$(FlotillaShieldAbsorption)"       Path="../ClassFlotilla"     Priority="1"/>
        
        <Modifier TargetProperty="HullPlatingAbsorption"   Operation="Addition" Value="$(FlotillaDmgReductionAgainstPhysical)" Path="../ClassFlotilla/ClassShipEncounter"  Priority="1"/>
        <Modifier TargetProperty="ShieldAbsorption"     Operation="Addition" Value="$(FlotillaDmgReductionAgainstEnergy)"   Path="../ClassFlotilla/ClassShipEncounter"  Priority="1"/>
        
        <!-- modded -->
        <!--<Modifier TargetProperty="DamageBonusPerTargetCommandPoints"     Operation="Addition" Value="$(DamageBonusPerTargetCommandPointsFlotilla)"   Path="../ClassFlotilla/ClassShipEncounter" />-->

        <Modifier TargetProperty="RepairAfterBattle"           Operation="Addition" Value="$(FlotillaRepairAfterBattle)"       Path="../ClassFlotilla/ClassShipEncounter"     Priority="1"/>
        <Modifier TargetProperty="RepairAfterPhase"            Operation="Addition" Value="$(FlotillaRepairAfterPhase)"        Path="../ClassFlotilla/ClassShipEncounter"     Priority="1"/>
        
        <Modifier TargetProperty="ShipManpowerKillPerHitPercentEncounter"       Operation="Addition" Value="$(FlotillaShipManpowerKillPerHitPercent)"        Path="../ClassFlotilla/ClassShipEncounter"     Priority="1"/>         
    </SimulationDescriptor>

</Datatable>

=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Simulation/SimulationDescriptors[Hacking_DLC3].xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Schemas/Amplitude.Unity.Simulation.SimulationDescriptor.xsd">

   <!-- Accelerator -->
   <SimulationDescriptor Name="HackingProgramEffectSpeedupHacking" Type="HackingProgramEffect">
      <Modifier TargetProperty="HackingSpeedMultiplierForSelf" Operation="Addition" Value="0.3"/>
   </SimulationDescriptor>
   
   <!-- Piggyback -->
    <SimulationDescriptor Name="HackingProgramEffectDecreaseHackerPPAllocation" Type="HackingProgramEffect">
        <Modifier TargetProperty="FinalProcessingPowerAllocation" Operation="Percent" Value="-0.5" Path="ClassEmpire/ClassHacking/!CostCannotBeBoostedByPrograms,ClassHackingProgram"/>
    </SimulationDescriptor>

   <!-- Divert -->
   <SimulationDescriptor Name="RerouteOffenseHackingProgramEffect" Type="RerouteOffenseHackingProgramEffect">
      <Modifier TargetProperty="BailiffPriority" Operation="Subtraction" Value="100" TooltipHidden="true"/>
   </SimulationDescriptor>
   
   <!-- Overload -->
   <SimulationDescriptor Name="HackingProgramEffectInstantIncreasePPAllocation" Type="HackingProgramEffect">
      <Modifier TargetProperty="FinalProcessingPowerAllocation" Operation="Percent" Value="1" Path="../ClassEmpire/ClassHacking/ClassHackingProgram" TooltipOverride="%HackingOffensiveProgramIncreasedPPAllocationEffectOverride"/>
   </SimulationDescriptor>
   
   
   
   
   <!-- Lockdown-->
   <SimulationDescriptor Name="HackingProgramEffectSlowndownTrace" Type="HackingProgramEffect">
      <Modifier TargetProperty="HackingNodeSpeed" Operation="Percent" Value="-0.25"/>
   </SimulationDescriptor>

   <!-- Encrypt -->
   <SimulationDescriptor Name="HackingProgramEffectSlowDownHacking" Type="HackingProgramEffect">
      <Modifier TargetProperty="HackingSpeedMultiplierForOthers" Operation="Subtraction" Value="0.5"/>
   </SimulationDescriptor>
   
   <!-- Interogate -->
    <SimulationDescriptor Name="HackingProgramEffectIncreaseHackerPPAllocation" Type="HackingProgramEffect">
        <Modifier TargetProperty="FinalProcessingPowerAllocation" Operation="Percent" Value="0.5" Path="ClassEmpire/ClassHacking/!CostCannotBeBoostedByPrograms,ClassHackingProgram"/>
    </SimulationDescriptor>

   <!-- Firewall -->
   <SimulationDescriptor Name="HackingProgramEffectHackingDefense" Type="HackingProgramEffect">
      <Modifier TargetProperty="HackingOperationOutcomeDefenseLevel" Operation="Addition" Value="1" TooltipOverride="%HackingProgramEffectHackingDefenseEffectOverride"/>
   </SimulationDescriptor>

   <!-- track -->
   
</Datatable>
