=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Schemas/Amplitude.Unity.Simulation.SimulationDescriptor.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Datatable" />
  <xs:element name="SimulationDescriptor" nillable="true" type="SimulationDescriptor" />
  <xs:complexType name="SimulationDescriptor">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="1" name="ProportionalProperty" type="SimulationPropertyDescriptor_Proportional" />
        <xs:element minOccurs="0" maxOccurs="1" name="Property" type="SimulationPropertyDescriptor" />
      </xs:choice>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="1" name="CountModifier" type="CountSimulationModifierDescriptor" />
        <xs:element minOccurs="0" maxOccurs="1" name="BinaryModifier" type="BinarySimulationModifierDescriptor" />
        <xs:element minOccurs="0" maxOccurs="1" name="Modifier" type="SingleSimulationModifierDescriptor" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute default="true" name="IsSerializable" type="xs:boolean" />
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="Type" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="SimulationPropertyDescriptor_Proportional">
    <xs:complexContent mixed="false">
      <xs:extension base="SimulationPropertyDescriptor">
        <xs:attribute name="Maximum" type="xs:string" />
        <xs:attribute name="Minimum" type="xs:string" />
        <xs:attribute name="StartingRatio" type="xs:float" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SimulationPropertyDescriptor">
    <xs:attribute default="0" name="BaseValue" type="xs:float" />
    <xs:attribute default="None" name="Composition" type="SimulationPropertyComposition" />
    <xs:attribute default="None" name="RoundingFunction" type="SimulationPropertyRoundingFunction" />
    <xs:attribute default="false" name="IsSealed" type="xs:boolean" />
    <xs:attribute default="false" name="IsSerializable" type="xs:boolean" />
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="MaxValue" type="xs:string" />
    <xs:attribute name="MinValue" type="xs:string" />
  </xs:complexType>
  <xs:simpleType name="SimulationPropertyComposition">
    <xs:restriction base="xs:string">
      <xs:enumeration value="None" />
      <xs:enumeration value="Maximum" />
      <xs:enumeration value="Minimum" />
      <xs:enumeration value="Sum" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="SimulationPropertyRoundingFunction">
    <xs:restriction base="xs:string">
      <xs:enumeration value="None" />
      <xs:enumeration value="Ceil" />
      <xs:enumeration value="Floor" />
      <xs:enumeration value="Round" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="CountSimulationModifierDescriptor">
    <xs:complexContent mixed="false">
      <xs:extension base="SimulationModifierDescriptor">
        <xs:attribute default="1" name="Multiplier" type="xs:string" />
        <xs:attribute name="CountPath" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SimulationModifierDescriptor">
    <xs:attribute default="false" name="SearchValueFromPath" type="xs:boolean" />
    <xs:attribute name="Operation" type="ModifierOperation" use="required" />
    <xs:attribute default="0" name="Priority" type="xs:float" />
    <xs:attribute default="" name="TooltipOverride" type="xs:string" />
    <xs:attribute default="false" name="TooltipHidden" type="xs:boolean" />
    <xs:attribute default="false" name="TooltipHiddenIfPathInvalid" type="xs:boolean" />
    <xs:attribute default="false" name="EnforceContext" type="xs:boolean" />
    <xs:attribute default="false" name="ValueMustBePositive" type="xs:boolean" />
    <xs:attribute default="false" name="UseIfInsteadOfWhere" type="xs:boolean" />
    <xs:attribute default="false" name="ForceFrom" type="xs:boolean" />
    <xs:attribute name="Path" type="xs:string" />
    <xs:attribute name="TargetProperty" type="xs:string" />
  </xs:complexType>
  <xs:simpleType name="ModifierOperation">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Force" />
      <xs:enumeration value="Addition" />
      <xs:enumeration value="Subtraction" />
      <xs:enumeration value="Multiplication" />
      <xs:enumeration value="Division" />
      <xs:enumeration value="Power" />
      <xs:enumeration value="Percent" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="BinarySimulationModifierDescriptor">
    <xs:complexContent mixed="false">
      <xs:extension base="SimulationModifierDescriptor">
        <xs:attribute name="BinaryOperation" type="ModifierOperation" use="required" />
        <xs:attribute name="Left" type="xs:string" />
        <xs:attribute name="Right" type="xs:string" />
        <xs:attribute default="false" name="EnforceRightAsPer" type="xs:boolean" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SingleSimulationModifierDescriptor">
    <xs:complexContent mixed="false">
      <xs:extension base="SimulationModifierDescriptor">
        <xs:attribute name="Value" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>

=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Simulation/SimulationDescriptors[EmpireImprovements_mod].xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Schemas/Amplitude.Unity.Simulation.SimulationDescriptor.xsd">
   
    <SimulationDescriptor Name="EmpireImprovementFood1"      Type="EmpireImprovement">
        <Modifier TargetProperty="SystemGrowth" Operation="Percent" Value="0.15"  Path="ClassEmpire/ClassColonizedStarSystem" />
    </SimulationDescriptor>

   <SimulationDescriptor Name="EmpireImprovementScience1"      Type="EmpireImprovement">
      
      <Modifier TargetProperty="SystemFIDSIFromEmpireImprovementScience1"     Operation="Addition" Value="35"  Path="ClassEmpire/ClassColonizedStarSystem" TooltipOverride="%SystemFIDSIFromEmpireImprovementScience1"/>
   </SimulationDescriptor>

   <SimulationDescriptor Name="EmpireImprovementScience2"      Type="EmpireImprovement">
      <Modifier TargetProperty="SystemResearch"   Operation="Percent"  Value="0.20" Path="ClassEmpire/ClassColonizedStarSystem" />
   </SimulationDescriptor>

   <SimulationDescriptor Name="EmpireImprovementScience3"      Type="EmpireImprovement">
      <BinaryModifier TargetProperty="SystemFIDSIFromEmpireImprovementScience3"     Operation="Addition" Left="0.025" BinaryOperation="Multiplication" Right="$(SystemLevel)" SearchValueFromPath="true" Path="ClassEmpire/ClassColonizedStarSystem" TooltipOverride="%SystemFIDSIFromEmpireImprovementScience3" />
   </SimulationDescriptor>

   <SimulationDescriptor Name="EmpireImprovementDust1"      Type="EmpireImprovement">
      <Modifier TargetProperty="SystemMoney" Operation="Percent" Value="0.05"  Path="ClassEmpire/ClassColonizedStarSystem,StarSystemImprovementLevel1" TooltipOverride="%TooltipOverrideEmpireImprovementDust1_1" />
      <Modifier TargetProperty="SystemMoney" Operation="Percent" Value="0.10"  Path="ClassEmpire/ClassColonizedStarSystem,StarSystemImprovementLevel2" TooltipOverride="%TooltipOverrideEmpireImprovementDust1_2" />
      <Modifier TargetProperty="SystemMoney" Operation="Percent" Value="0.20"  Path="ClassEmpire/ClassColonizedStarSystem,StarSystemImprovementLevel3" TooltipOverride="%TooltipOverrideEmpireImprovementDust1_3" />
      <Modifier TargetProperty="SystemMoney" Operation="Percent" Value="0.40"  Path="ClassEmpire/ClassColonizedStarSystem,StarSystemImprovementLevel4" TooltipOverride="%TooltipOverrideEmpireImprovementDust1_4" />
   </SimulationDescriptor>

   <SimulationDescriptor Name="EmpireImprovementDust2"      Type="EmpireImprovement">
      <Modifier TargetProperty="SystemMoney" Operation="Percent" Value="0.20"  Path="ClassEmpire/ClassColonizedStarSystem" />
   </SimulationDescriptor>

   <SimulationDescriptor Name="EmpireImprovementDust3"      Type="EmpireImprovement">
      <BinaryModifier TargetProperty="SystemMoney"              Operation="Percent"  Left="0.40" BinaryOperation="Multiplication" Right="$(NumberOfTradingCompanies)" Path="ClassEmpire/ClassColonizedStarSystem" SearchValueFromPath="true"/>
   </SimulationDescriptor>

   <SimulationDescriptor Name="EmpireImprovementDust4"      Type="EmpireImprovement">
      <BinaryModifier TargetProperty="SystemResearch"              Operation="Percent"  Left="0.40" BinaryOperation="Multiplication" Right="$(NumberOfTradingCompanies)" Path="ClassEmpire/ClassColonizedStarSystem" SearchValueFromPath="true"/>
   </SimulationDescriptor>

   <SimulationDescriptor Name="EmpireImprovementInfluence1"    Type="EmpireImprovement">
      <Modifier TargetProperty="BasePressureMultiplier" Operation="Percent" Value="0.20" Path="../ClassEmpire/ClassDiplomacy" TooltipOverride="%TooltipOverrideEmpireImprovementInfluence1" />
      <Modifier TargetProperty="SystemEmpirePoint"      Operation="Percent" Value="0.15"  Path="ClassEmpire/ClassColonizedStarSystem" />
   </SimulationDescriptor>

   <SimulationDescriptor Name="EmpireImprovementArkShipMovement1" Type="EmpireImprovement">
      <Modifier TargetProperty="MaximumMovement" Operation="Addition" Value="5" Path="AffinityGameplayVampirilis,ClassEmpire/ClassGarrisonFleet/ClassShip,ShipRoleMothership" />
   </SimulationDescriptor>
   <SimulationDescriptor Name="EmpireImprovementArkShipMovement2" Type="EmpireImprovement">
      <Modifier TargetProperty="MaximumMovement" Operation="Addition" Value="5" Path="AffinityGameplayVampirilis,ClassEmpire/ClassGarrisonFleet/ClassShip,ShipRoleMothership" />
   </SimulationDescriptor>
   <SimulationDescriptor Name="EmpireImprovementArkShipMovement3" Type="EmpireImprovement">
      <Modifier TargetProperty="MaximumMovement" Operation="Addition" Value="10" Path="AffinityGameplayVampirilis,ClassEmpire/ClassGarrisonFleet/ClassShip,ShipRoleMothership" />
   </SimulationDescriptor>

  </Datatable>

=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Simulation/SimulationDescriptors[Government].xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Schemas/Amplitude.Unity.Simulation.SimulationDescriptor.xsd">

    <!-- DICTATORSHIP -->
    <SimulationDescriptor Name="GovernmentDictatorshipCommon" Type="GovernmentDictatorshipCommon"/>

    <SimulationDescriptor Name="GovernmentDictatorship" Type="Government">
        <Modifier TargetProperty="HappinessStatusMinimumRebellionIndex"    Operation="Addition"     Value="1"      Path="./ClassEmpire" TooltipOverride="%GovernmentDictatorshipTooltipEffect"   />

        <Modifier TargetProperty="NumberOfSenatorSlots"                 Operation="Force"           Value="1"                           Path="ClassSenate"   />
        <!--Unassigned heroes-->
        <Modifier TargetProperty="SenatorSkillEffectDictatorshipMultiplier" Operation="Multiplication" Value="2" Path="../ClassEmpire/ClassHero"/>
        <!--Governors-->
        <Modifier TargetProperty="SenatorSkillEffectDictatorshipMultiplier" Operation="Multiplication" Value="2" Path="../ClassEmpire/ClassColonizedStarSystem/ClassHero,HeroAssignedToSystem" TooltipHidden="true"/>
        <!--Admirals-->
        <Modifier TargetProperty="SenatorSkillEffectDictatorshipMultiplier" Operation="Multiplication" Value="2" Path="../ClassEmpire/ClassGarrisonFleet/ClassHero,HeroAssignedToFleet" TooltipHidden="true"/>
    </SimulationDescriptor>

    
    <SimulationDescriptor Name="GovernmentDictatorshipCravers" Type="Government">
        <Modifier TargetProperty="HappinessStatusMinimumRebellionIndex"    Operation="Addition"     Value="-1"      Path="./ClassEmpire" TooltipOverride="%GovernmentDictatorshipCraversTooltipEffect"   />
        <Modifier TargetProperty="GovernmentGameplayLocked"                 Operation="Addition"    Value="1"       Path="./ClassEmpire" TooltipHidden="true"/>

        <Modifier TargetProperty="NumberOfSenatorSlots"                 Operation="Force"       Value="1"      Path="ClassSenate"   />
        <Modifier TargetProperty="NumberOfActiveLawSlots"               Operation="Addition"    Value="1"      Path="ClassSenate"   />
        <!--Unassigned heroes-->
        <Modifier TargetProperty="SenatorSkillEffectDictatorshipMultiplier" Operation="Multiplication" Value="2" Path="../ClassEmpire/ClassHero"/>
        <!--Governors-->
        <Modifier TargetProperty="SenatorSkillEffectDictatorshipMultiplier" Operation="Multiplication" Value="2" Path="../ClassEmpire/ClassColonizedStarSystem/ClassHero,HeroAssignedToSystem" TooltipHidden="true"/>
        <!--Admirals-->
        <Modifier TargetProperty="SenatorSkillEffectDictatorshipMultiplier" Operation="Multiplication" Value="2" Path="../ClassEmpire/ClassGarrisonFleet/ClassHero,HeroAssignedToFleet" TooltipHidden="true"/>

        <Modifier TargetProperty="Politics01ToPolitics01"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics01ToPolitics02"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics01ToPolitics03"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics01ToPolitics04"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics01ToPolitics05"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics01ToPolitics06"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics02ToPolitics01"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics02ToPolitics02"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics02ToPolitics03"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics02ToPolitics04"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics02ToPolitics05"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics02ToPolitics06"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics03ToPolitics01"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics03ToPolitics02"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics03ToPolitics03"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics03ToPolitics04"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics03ToPolitics05"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics03ToPolitics06"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics04ToPolitics01"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics04ToPolitics02"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics04ToPolitics03"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics04ToPolitics04"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics04ToPolitics05"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics04ToPolitics06"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics05ToPolitics01"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics05ToPolitics02"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics05ToPolitics03"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics05ToPolitics04"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics05ToPolitics05"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics05ToPolitics06"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics06ToPolitics01"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics06ToPolitics02"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics06ToPolitics03"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics06ToPolitics04"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics06ToPolitics05"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
        <Modifier TargetProperty="Politics06ToPolitics06"   Operation="Force"  Value="0"    TooltipHidden="true"    Path="./ClassEmpire/ClassPopulationEmpire,PopulationNonMajor"/>
    </SimulationDescriptor>

</Datatable>

=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Simulation/SimulationDescriptors[ManpowerUpgrade].xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Schemas/Amplitude.Unity.Simulation.SimulationDescriptor.xsd">

  <!-- Infantry -->
  <SimulationDescriptor Name="ManpowerUpgradeInfantry1" Type="ManpowerUpgrade">
      <Modifier TargetProperty="InfantryDamagesMultiplierAgainstPlane" Operation="Addition"   Value="1" Path="ClassEmpire"  />
      <Modifier TargetProperty="EmpireInfantryLevel" Operation="Addition" Value="1" Path="ClassEmpire//ClassShip" TooltipHidden="true"/>
  </SimulationDescriptor>

  <SimulationDescriptor Name="ManpowerUpgradeInfantry2" Type="ManpowerUpgrade">
		<Modifier TargetProperty="InfantryMaxHealth"  Operation="Percent" Value="0.5" Path="ClassEmpire"/>    
		<Modifier TargetProperty="InfantryDamagesBonus" Operation="Addition" Value="0.25" Path="ClassEmpire"/>
    <Modifier TargetProperty="EmpireInfantryLevel" Operation="Addition" Value="1" Path="ClassEmpire//ClassShip" TooltipHidden="true"/>
	</SimulationDescriptor>

	<SimulationDescriptor Name="ManpowerUpgradeInfantry3" Type="ManpowerUpgrade">
      <Modifier TargetProperty="InfantryMaxHealth"    Operation="Percent"  Value="1" Path="ClassEmpire"/>
      <Modifier TargetProperty="InfantryDamagesBonus" Operation="Addition" Value="0.5" Path="ClassEmpire"/>
      <Modifier TargetProperty="EmpireInfantryLevel" Operation="Addition" Value="1" Path="ClassEmpire//ClassShip" TooltipHidden="true"/>
  </SimulationDescriptor>

  <SimulationDescriptor Name="ManpowerUpgradeInfantry4" Type="ManpowerUpgrade">
		<Modifier TargetProperty="InfantryDamagesMultiplierAgainstPlane" Operation="Addition" Value="1" Path="ClassEmpire"/>
    <Modifier TargetProperty="InfantryMaxHealth"                     Operation="Percent"  Value="1.5" Path="ClassEmpire"/>
    <Modifier TargetProperty="EmpireInfantryLevel" Operation="Addition" Value="1" Path="ClassEmpire//ClassShip" TooltipHidden="true"/>
	</SimulationDescriptor>

	<SimulationDescriptor Name="ManpowerUpgradeInfantry5" Type="ManpowerUpgrade">
		<Modifier TargetProperty="InfantryMaxHealth"    Operation="Percent"  Value="2" Path="ClassEmpire" />
    <Modifier TargetProperty="InfantryDamagesBonus" Operation="Addition" Value="1" Path="ClassEmpire" />
    <Modifier TargetProperty="EmpireInfantryLevel" Operation="Addition" Value="1" Path="ClassEmpire//ClassShip" TooltipHidden="true"/>
  </SimulationDescriptor>

  <!-- Tank -->
  <SimulationDescriptor Name="ManpowerUpgradeTank1" Type="ManpowerUpgrade">
    <Modifier TargetProperty="TankDamagesMultiplierAgainstInfantry" Operation="Addition" Value="1" Path="ClassEmpire" />
  </SimulationDescriptor>

	<SimulationDescriptor Name="ManpowerUpgradeTank2" Type="ManpowerUpgrade">
    <Modifier TargetProperty="TankMaxHealth"    Operation="Percent"  Value="0.5"  Path="ClassEmpire"/>
    <Modifier TargetProperty="TankDamagesBonus" Operation="Addition" Value="0.25" Path="ClassEmpire"/>
  </SimulationDescriptor>

  <SimulationDescriptor Name="ManpowerUpgradeTank3" Type="ManpowerUpgrade">
    <Modifier TargetProperty="TankMaxHealth" Operation="Percent"     Value="1" Path="ClassEmpire"/>
    <Modifier TargetProperty="TankDamagesBonus" Operation="Addition" Value="0.5" Path="ClassEmpire"/>
  </SimulationDescriptor>

  <SimulationDescriptor Name="ManpowerUpgradeTank4" Type="ManpowerUpgrade">
		<Modifier TargetProperty="TankDamagesMultiplierAgainstInfantry" Operation="Addition" Value="1" Path="ClassEmpire" />
    <Modifier TargetProperty="TankMaxHealth" Operation="Percent"     Value="1.5" Path="ClassEmpire"/>
  </SimulationDescriptor>

  <SimulationDescriptor Name="ManpowerUpgradeTank5" Type="ManpowerUpgrade">
		<Modifier TargetProperty="TankMaxHealth"    Operation="Percent"  Value="2" Path="ClassEmpire"/>
    <Modifier TargetProperty="TankDamagesBonus" Operation="Addition" Value="1"    Path="ClassEmpire"/>
  </SimulationDescriptor>

  <!-- Plane -->
  <SimulationDescriptor Name="ManpowerUpgradePlane1" Type="ManpowerUpgrade">
    <Modifier TargetProperty="PlaneDamagesMultiplierAgainstTank" Operation="Addition" Value="1" Path="ClassEmpire" />
  </SimulationDescriptor>

  <SimulationDescriptor Name="ManpowerUpgradePlane2" Type="ManpowerUpgrade">
    <Modifier TargetProperty="PlaneMaxHealth"    Operation="Percent"  Value="0.5" Path="ClassEmpire"/>
    <Modifier TargetProperty="PlaneDamagesBonus" Operation="Addition" Value="0.25" Path="ClassEmpire"/>
	</SimulationDescriptor>

	<SimulationDescriptor Name="ManpowerUpgradePlane3" Type="ManpowerUpgrade">
    <Modifier TargetProperty="PlaneMaxHealth"    Operation="Percent"  Value="1" Path="ClassEmpire"/>
    <Modifier TargetProperty="PlaneDamagesBonus" Operation="Addition" Value="0.5" Path="ClassEmpire"/>
	</SimulationDescriptor>

	<SimulationDescriptor Name="ManpowerUpgradePlane4" Type="ManpowerUpgrade">
		<Modifier TargetProperty="PlaneDamagesMultiplierAgainstTank" Operation="Addition" Value="1" Path="ClassEmpire" />
    <Modifier TargetProperty="PlaneMaxHealth"                    Operation="Percent"  Value="1.5" Path="ClassEmpire"/>
	</SimulationDescriptor>

	<SimulationDescriptor Name="ManpowerUpgradePlane5" Type="ManpowerUpgrade">
		<Modifier TargetProperty="PlaneMaxHealth"    Operation="Percent"  Value="2" Path="ClassEmpire"/>
    <Modifier TargetProperty="PlaneDamagesBonus" Operation="Addition" Value="1" Path="ClassEmpire"/>
  </SimulationDescriptor>

</Datatable>
