=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Schemas/Amplitude.Unity.Simulation.SimulationDescriptor.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Datatable" />
  <xs:element name="SimulationDescriptor" nillable="true" type="SimulationDescriptor" />
  <xs:complexType name="SimulationDescriptor">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="1" name="ProportionalProperty" type="SimulationPropertyDescriptor_Proportional" />
        <xs:element minOccurs="0" maxOccurs="1" name="Property" type="SimulationPropertyDescriptor" />
      </xs:choice>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="1" name="CountModifier" type="CountSimulationModifierDescriptor" />
        <xs:element minOccurs="0" maxOccurs="1" name="BinaryModifier" type="BinarySimulationModifierDescriptor" />
        <xs:element minOccurs="0" maxOccurs="1" name="Modifier" type="SingleSimulationModifierDescriptor" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute default="true" name="IsSerializable" type="xs:boolean" />
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="Type" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="SimulationPropertyDescriptor_Proportional">
    <xs:complexContent mixed="false">
      <xs:extension base="SimulationPropertyDescriptor">
        <xs:attribute name="Maximum" type="xs:string" />
        <xs:attribute name="Minimum" type="xs:string" />
        <xs:attribute name="StartingRatio" type="xs:float" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SimulationPropertyDescriptor">
    <xs:attribute default="0" name="BaseValue" type="xs:float" />
    <xs:attribute default="None" name="Composition" type="SimulationPropertyComposition" />
    <xs:attribute default="None" name="RoundingFunction" type="SimulationPropertyRoundingFunction" />
    <xs:attribute default="false" name="IsSealed" type="xs:boolean" />
    <xs:attribute default="false" name="IsSerializable" type="xs:boolean" />
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="MaxValue" type="xs:string" />
    <xs:attribute name="MinValue" type="xs:string" />
  </xs:complexType>
  <xs:simpleType name="SimulationPropertyComposition">
    <xs:restriction base="xs:string">
      <xs:enumeration value="None" />
      <xs:enumeration value="Maximum" />
      <xs:enumeration value="Minimum" />
      <xs:enumeration value="Sum" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="SimulationPropertyRoundingFunction">
    <xs:restriction base="xs:string">
      <xs:enumeration value="None" />
      <xs:enumeration value="Ceil" />
      <xs:enumeration value="Floor" />
      <xs:enumeration value="Round" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="CountSimulationModifierDescriptor">
    <xs:complexContent mixed="false">
      <xs:extension base="SimulationModifierDescriptor">
        <xs:attribute default="1" name="Multiplier" type="xs:string" />
        <xs:attribute name="CountPath" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SimulationModifierDescriptor">
    <xs:attribute default="false" name="SearchValueFromPath" type="xs:boolean" />
    <xs:attribute name="Operation" type="ModifierOperation" use="required" />
    <xs:attribute default="0" name="Priority" type="xs:float" />
    <xs:attribute default="" name="TooltipOverride" type="xs:string" />
    <xs:attribute default="false" name="TooltipHidden" type="xs:boolean" />
    <xs:attribute default="false" name="TooltipHiddenIfPathInvalid" type="xs:boolean" />
    <xs:attribute default="false" name="EnforceContext" type="xs:boolean" />
    <xs:attribute default="false" name="ValueMustBePositive" type="xs:boolean" />
    <xs:attribute default="false" name="UseIfInsteadOfWhere" type="xs:boolean" />
    <xs:attribute default="false" name="ForceFrom" type="xs:boolean" />
    <xs:attribute name="Path" type="xs:string" />
    <xs:attribute name="TargetProperty" type="xs:string" />
  </xs:complexType>
  <xs:simpleType name="ModifierOperation">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Force" />
      <xs:enumeration value="Addition" />
      <xs:enumeration value="Subtraction" />
      <xs:enumeration value="Multiplication" />
      <xs:enumeration value="Division" />
      <xs:enumeration value="Power" />
      <xs:enumeration value="Percent" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="BinarySimulationModifierDescriptor">
    <xs:complexContent mixed="false">
      <xs:extension base="SimulationModifierDescriptor">
        <xs:attribute name="BinaryOperation" type="ModifierOperation" use="required" />
        <xs:attribute name="Left" type="xs:string" />
        <xs:attribute name="Right" type="xs:string" />
        <xs:attribute default="false" name="EnforceRightAsPer" type="xs:boolean" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SingleSimulationModifierDescriptor">
    <xs:complexContent mixed="false">
      <xs:extension base="SimulationModifierDescriptor">
        <xs:attribute name="Value" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>

=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Simulation/SimulationDescriptors[SpecialNodes].xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Schemas/Amplitude.Unity.Simulation.SimulationDescriptor.xsd">

    <SimulationDescriptor Name="SpecialNodeEffectBlackHole" Type="SpecialNodeEffect" IsSerializable="false">
        <Modifier TargetProperty="SystemResearchPercent"       Operation="Addition" Value="0.1" TooltipHidden="true" />
        <Modifier TargetProperty="SystemResearchPercent"       Operation="Addition" Value="0.1" Path="../ClassHackingBeacon/../ClassEmpire/ClassColonizedStarSystem,ColonizedStarSystemStateColony" TooltipHiddenIfPathInvalid="true" />
        <Modifier TargetProperty="SystemResearch"              Operation="Percent"  Value="0.1" Path="../ClassEmpire/ClassColonizedStarSystem,FAKEFORGUISystems"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="SpecialNodeEffectAsteroidField" Type="SpecialNodeEffect" IsSerializable="false">
        <Modifier TargetProperty="SystemProductionPercent"     Operation="Addition" Value="0.1" TooltipHidden="true" />
        <Modifier TargetProperty="SystemProductionPercent"     Operation="Addition" Value="0.1" Path="../ClassHackingBeacon/../ClassEmpire/ClassColonizedStarSystem,ColonizedStarSystemStateColony" TooltipHiddenIfPathInvalid="true" />
        <Modifier TargetProperty="SystemProduction"            Operation="Percent"  Value="0.1" Path="../ClassEmpire/ClassColonizedStarSystem,FAKEFORGUISystems"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="SpecialNodeEffectCollapsingStar" Type="SpecialNodeEffect" IsSerializable="false">
        <Modifier TargetProperty="SystemEmpirePointPercent"    Operation="Addition" Value="0.1" TooltipHidden="true"  />
        <Modifier TargetProperty="SystemEmpirePointPercent"    Operation="Addition" Value="0.1" Path="../ClassHackingBeacon/../ClassEmpire/ClassColonizedStarSystem,ColonizedStarSystemStateColony" TooltipHiddenIfPathInvalid="true" />
        <Modifier TargetProperty="SystemEmpirePoint"           Operation="Percent"  Value="0.1" Path="../ClassEmpire/ClassColonizedStarSystem,FAKEFORGUISystems" />
    </SimulationDescriptor>

    <SimulationDescriptor Name="SpecialNodeEffectSolarNebula" Type="SpecialNodeEffect" IsSerializable="false">
        <Modifier TargetProperty="SystemMoneyPercent"          Operation="Addition" Value="0.1" TooltipHidden="true" />
        <Modifier TargetProperty="SystemMoneyPercent"          Operation="Addition" Value="0.1" Path="../ClassHackingBeacon/../ClassEmpire/ClassColonizedStarSystem,ColonizedStarSystemStateColony" TooltipHiddenIfPathInvalid="true" />
        <Modifier TargetProperty="SystemMoney"                 Operation="Percent"  Value="0.1" Path="../ClassEmpire/ClassColonizedStarSystem,FAKEFORGUISystems"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="SpecialNodeEffectNeutronStar" Type="SpecialNodeEffect" IsSerializable="false">
        <Modifier TargetProperty="SystemMoneyPercent"          Operation="Addition" Value="0.05" TooltipHidden="true" />
        <Modifier TargetProperty="SystemEmpirePointPercent"    Operation="Addition" Value="0.05" TooltipHidden="true" />
        <Modifier TargetProperty="SystemMoneyPercent"          Operation="Addition" Value="0.05" Path="../ClassHackingBeacon/../ClassEmpire/ClassColonizedStarSystem,ColonizedStarSystemStateColony" TooltipHiddenIfPathInvalid="true" />
        <Modifier TargetProperty="SystemEmpirePointPercent"    Operation="Addition" Value="0.05" Path="../ClassHackingBeacon/../ClassEmpire/ClassColonizedStarSystem,ColonizedStarSystemStateColony" TooltipHiddenIfPathInvalid="true" />
        <Modifier TargetProperty="SystemMoney"                 Operation="Percent"  Value="0.05" Path="../ClassEmpire/ClassColonizedStarSystem,FAKEFORGUISystems"/>
        <Modifier TargetProperty="SystemEmpirePoint"           Operation="Percent"  Value="0.05" Path="../ClassEmpire/ClassColonizedStarSystem,FAKEFORGUISystems"/>
	</SimulationDescriptor>

    <SimulationDescriptor Name="SpecialNodeEffectSpaceClouds" Type="SpecialNodeEffect" IsSerializable="false">
        <Modifier TargetProperty="SystemMoneyPercent"          Operation="Addition" Value="0.02" TooltipHidden="true" />
        <Modifier TargetProperty="SystemEmpirePointPercent"    Operation="Addition" Value="0.02" TooltipHidden="true" />
        <Modifier TargetProperty="SystemProductionPercent"     Operation="Addition" Value="0.02" TooltipHidden="true" />
        <Modifier TargetProperty="SystemResearchPercent"       Operation="Addition" Value="0.02" TooltipHidden="true" />
        <Modifier TargetProperty="SystemMoneyPercent"          Operation="Addition" Value="0.02" Path="../ClassHackingBeacon/../ClassEmpire/ClassColonizedStarSystem,ColonizedStarSystemStateColony" TooltipHiddenIfPathInvalid="true" />
        <Modifier TargetProperty="SystemEmpirePointPercent"    Operation="Addition" Value="0.02" Path="../ClassHackingBeacon/../ClassEmpire/ClassColonizedStarSystem,ColonizedStarSystemStateColony" TooltipHiddenIfPathInvalid="true" />
        <Modifier TargetProperty="SystemProductionPercent"     Operation="Addition" Value="0.02" Path="../ClassHackingBeacon/../ClassEmpire/ClassColonizedStarSystem,ColonizedStarSystemStateColony" TooltipHiddenIfPathInvalid="true" />
        <Modifier TargetProperty="SystemResearchPercent"       Operation="Addition" Value="0.02" Path="../ClassHackingBeacon/../ClassEmpire/ClassColonizedStarSystem,ColonizedStarSystemStateColony" TooltipHiddenIfPathInvalid="true" />
        <Modifier TargetProperty="SystemMoney"                 Operation="Percent"  Value="0.02" Path="../ClassEmpire/ClassColonizedStarSystem,FAKEFORGUISystems"/>
        <Modifier TargetProperty="SystemEmpirePoint"           Operation="Percent"  Value="0.02" Path="../ClassEmpire/ClassColonizedStarSystem,FAKEFORGUISystems"/>
        <Modifier TargetProperty="SystemProduction"            Operation="Percent"  Value="0.02" Path="../ClassEmpire/ClassColonizedStarSystem,FAKEFORGUISystems"/>
        <Modifier TargetProperty="SystemResearch"              Operation="Percent"  Value="0.02" Path="../ClassEmpire/ClassColonizedStarSystem,FAKEFORGUISystems"/>
    </SimulationDescriptor>
    
    <SimulationDescriptor Name="SpecialNodeEffectVaulters" Type="SpecialNodeEffect" IsSerializable="false">
        <Modifier TargetProperty="SystemMoneyPercent"          Operation="Addition" Value="0.15" TooltipHidden="true" />
        <Modifier TargetProperty="HealthRegenerationRatio" Operation="Addition" Value="0.2" TooltipHidden="true" />
        <Modifier TargetProperty="DockedFleetsHealthRegenerationRatio" Operation="Addition" Value="0.2" TooltipOverride="%StarSystemImprovementUniqueCuriosity3EffectOverride"/>

        <Modifier TargetProperty="SystemMoney"          Operation="Percent" Value="0.15" Path="../ClassEmpire/ClassColonizedStarSystem,FAKEFORGUISystems"/>
    </SimulationDescriptor>
   
</Datatable>

=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Simulation/Battles/SimulationDescriptors[ModuleUpdate12].xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../../Schemas/Amplitude.Unity.Simulation.SimulationDescriptor.xsd">

    <!-- Better Speed Quest Modules  -->    
    <SimulationDescriptor Name="ModuleIncreasedSpeedQuest" Type="ModuleIncreasedSpeedQuest">
        <Property Name="MaximumMovement"/>
        <Property Name="GlobalSpeedBonus"/>

        <Modifier TargetProperty="MaximumMovement"                 Operation="Addition"    Value="$(MaximumMovement)"                   Path="../ClassShip"/>
        <Modifier TargetProperty="MaximumMovement"                 Operation="Percent"     Value="$(GlobalSpeedBonus)"                  Path="../ClassShip"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="ModuleIncreasedSpeedQuest01" Type="ModuleIncreasedSpeedQuest">
        <Modifier TargetProperty="MaximumMovement"                  Operation="Addition"    Value="3"       Path="ModuleIncreasedSpeedQuest"/>
        <Modifier TargetProperty="GlobalSpeedBonus"                 Operation="Addition"    Value="0.25"    Path="ModuleIncreasedSpeedQuest"/>
    </SimulationDescriptor>

</Datatable>

=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Simulation/Battles/SimulationDescriptors[Mothership].xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../../Schemas/Amplitude.Unity.Simulation.SimulationDescriptor.xsd">

    <!-- ****************************************** -->
    <!-- *****   FIDSI boost for MotherShip    **** -->
    <!-- ****************************************** -->

    <!--FIDSI-->
    <SimulationDescriptor Name ="ModuleStarSystemEffectFromMothership" Type="ModuleStarSystemEffectFromMothership">
        <Property Name="SystemLifeforceFlat"   BaseValue="0"/>
        <Property Name="SystemProductionFlat"   BaseValue="0"/>
        <Property Name="SystemProductionPercent"   BaseValue="0"/>
        <Property Name="SystemMoneyFlat"        BaseValue="0"/>
        <Property Name="SystemMoneyPercent"        BaseValue="0"/>
        <Property Name="SystemResearchFlat"     BaseValue="0"/>
        <Property Name="SystemResearchPercent"     BaseValue="0"/>
        <Property Name="SystemEmpirePointFlat"  BaseValue="0"/>
        <Property Name="SystemEmpirePointPercent"  BaseValue="0"/>
    </SimulationDescriptor>

    <!-- Dust -->
    <SimulationDescriptor Name="ModuleMothershipDust1" Type="ModuleMothershipDust">
        <Modifier TargetProperty="SystemMoneyFlat"  Operation="Addition" Value="10" Path="ModuleStarSystemEffectFromMothership"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="ModuleMothershipDust2" Type="ModuleMothershipDust">
        <Modifier TargetProperty="SystemMoneyFlat"         Operation="Addition" Value="20" Path="ModuleStarSystemEffectFromMothership"/>
        <Modifier TargetProperty="SystemMoneyPercent"      Operation="Addition" Value="0.01" Path="ModuleStarSystemEffectFromMothership"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="ModuleMothershipDust3" Type="ModuleMothershipDust">
        <Modifier TargetProperty="SystemMoneyFlat"         Operation="Addition" Value="35" Path="ModuleStarSystemEffectFromMothership"/>
        <Modifier TargetProperty="SystemMoneyPercent"      Operation="Addition" Value="0.05" Path="ModuleStarSystemEffectFromMothership"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="ModuleMothershipDust4" Type="ModuleMothershipDust">
        <Modifier TargetProperty="SystemMoneyFlat"         Operation="Addition" Value="50"     Path="ModuleStarSystemEffectFromMothership"/>
        <Modifier TargetProperty="SystemMoneyPercent"      Operation="Addition" Value="0.10"   Path="ModuleStarSystemEffectFromMothership"/>
    </SimulationDescriptor>

    <!-- Industry -->
    <SimulationDescriptor Name="ModuleMothershipIndustry1" Type="ModuleMothershipIndustry">
        <Modifier TargetProperty="SystemProductionFlat"  Operation="Addition" Value="10" Path="ModuleStarSystemEffectFromMothership"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="ModuleMothershipIndustry2" Type="ModuleMothershipIndustry">
        <Modifier TargetProperty="SystemProductionFlat"         Operation="Addition" Value="20" Path="ModuleStarSystemEffectFromMothership"/>
        <Modifier TargetProperty="SystemProductionPercent"      Operation="Addition" Value="0.01" Path="ModuleStarSystemEffectFromMothership"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="ModuleMothershipIndustry3" Type="ModuleMothershipIndustry">
        <Modifier TargetProperty="SystemProductionFlat"         Operation="Addition" Value="35" Path="ModuleStarSystemEffectFromMothership"/>
        <Modifier TargetProperty="SystemProductionPercent"      Operation="Addition" Value="0.05" Path="ModuleStarSystemEffectFromMothership"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="ModuleMothershipIndustry4" Type="ModuleMothershipIndustry">
        <Modifier TargetProperty="SystemProductionFlat"         Operation="Addition" Value="50"     Path="ModuleStarSystemEffectFromMothership"/>
        <Modifier TargetProperty="SystemProductionPercent"      Operation="Addition" Value="0.1"   Path="ModuleStarSystemEffectFromMothership"/>
    </SimulationDescriptor>

    <!-- Influence -->
    <SimulationDescriptor Name="ModuleMothershipInfluence1" Type="ModuleMothershipInfluence">
        <Modifier TargetProperty="SystemEmpirePointFlat"  Operation="Addition" Value="10" Path="ModuleStarSystemEffectFromMothership"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="ModuleMothershipInfluence2" Type="ModuleMothershipInfluence">
        <Modifier TargetProperty="SystemEmpirePointFlat"         Operation="Addition" Value="35" Path="ModuleStarSystemEffectFromMothership"/>
        <Modifier TargetProperty="SystemEmpirePointPercent"      Operation="Addition" Value="0.05" Path="ModuleStarSystemEffectFromMothership"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="ModuleMothershipInfluence3" Type="ModuleMothershipInfluence">
        <Modifier TargetProperty="SystemEmpirePointFlat"         Operation="Addition" Value="50" Path="ModuleStarSystemEffectFromMothership"/>
        <Modifier TargetProperty="SystemEmpirePointPercent"      Operation="Addition" Value="0.10" Path="ModuleStarSystemEffectFromMothership"/>
    </SimulationDescriptor>


    <!-- Lifeforce -->
    <SimulationDescriptor Name="ModuleMothershipLifeforce1" Type="ModuleMothershipLifeforce">
        <Modifier TargetProperty="SystemLifeforceFlat"  Operation="Addition" Value="10" Path="ModuleStarSystemEffectFromMothership"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="ModuleMothershipLifeforce2" Type="ModuleMothershipLifeforce">
        <Modifier TargetProperty="SystemLifeforceFlat"         Operation="Addition" Value="25" Path="ModuleStarSystemEffectFromMothership"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="ModuleMothershipLifeforce3" Type="ModuleMothershipLifeforce">
        <Modifier TargetProperty="SystemLifeforceFlat"         Operation="Addition" Value="40" Path="ModuleStarSystemEffectFromMothership"/>
    </SimulationDescriptor>

    <!-- Science -->
    <SimulationDescriptor Name="ModuleMothershipScience1" Type="ModuleMothershipScience">
        <Modifier TargetProperty="SystemResearchFlat"  Operation="Addition" Value="10" Path="ModuleStarSystemEffectFromMothership"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="ModuleMothershipScience2" Type="ModuleMothershipScience">
        <Modifier TargetProperty="SystemResearchFlat"         Operation="Addition" Value="20" Path="ModuleStarSystemEffectFromMothership"/>
        <Modifier TargetProperty="SystemResearchPercent"      Operation="Addition" Value="0.01" Path="ModuleStarSystemEffectFromMothership"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="ModuleMothershipScience3" Type="ModuleMothershipScience">
        <Modifier TargetProperty="SystemResearchFlat"         Operation="Addition" Value="35" Path="ModuleStarSystemEffectFromMothership"/>
        <Modifier TargetProperty="SystemResearchPercent"      Operation="Addition" Value="0.05" Path="ModuleStarSystemEffectFromMothership"/>
    </SimulationDescriptor>

    <SimulationDescriptor Name="ModuleMothershipScience4" Type="ModuleMothershipScience">
        <Modifier TargetProperty="SystemResearchFlat"         Operation="Addition" Value="50"     Path="ModuleStarSystemEffectFromMothership"/>
        <Modifier TargetProperty="SystemResearchPercent"      Operation="Addition" Value="0.1"   Path="ModuleStarSystemEffectFromMothership"/>
    </SimulationDescriptor>

</Datatable>

=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Simulation/SimulationDescriptors[FactionTrait].xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Schemas/Amplitude.Unity.Simulation.SimulationDescriptor.xsd">

    
	<SimulationDescriptor Name="FactionTraitInimical" Type="FactionTrait"> <!--Biophobic-->
      <!--Biophobic-->

      <!-- monsoon, atoll  2 happiness > -2-->
      <BinaryModifier  TargetProperty="Happiness"  Operation="Addition" Left="-4" BinaryOperation="Multiplication" Right="$(MajorPopulationCount)"    Path="ClassEmpire/ClassColonizedStarSystem/PlanetTypeMonsoon" SearchValueFromPath="true"  />
      <BinaryModifier  TargetProperty="Happiness"  Operation="Addition" Left="-4" BinaryOperation="Multiplication" Right="$(MajorPopulationCount)"    Path="ClassEmpire/ClassColonizedStarSystem/PlanetTypeAtoll"   SearchValueFromPath="true"  />
    
      <!-- jungle, ocean 5 happiness > -5 -->
      <BinaryModifier  TargetProperty="Happiness"  Operation="Addition" Left="-10" BinaryOperation="Multiplication" Right="$(MajorPopulationCount)"    Path="ClassEmpire/ClassColonizedStarSystem/PlanetTypeJungle"  SearchValueFromPath="true"  />
      <BinaryModifier  TargetProperty="Happiness"  Operation="Addition" Left="-10" BinaryOperation="Multiplication" Right="$(MajorPopulationCount)"    Path="ClassEmpire/ClassColonizedStarSystem/PlanetTypeOcean"   SearchValueFromPath="true"  />

      <!-- forrest, terran 8 happiness > -8 -->
      <BinaryModifier  TargetProperty="Happiness"  Operation="Addition" Left="-16" BinaryOperation="Multiplication" Right="$(MajorPopulationCount)"   Path="ClassEmpire/ClassColonizedStarSystem/PlanetTypeForest"  SearchValueFromPath="true"  />
      <BinaryModifier  TargetProperty="Happiness"  Operation="Addition" Left="-16" BinaryOperation="Multiplication" Right="$(MajorPopulationCount)"   Path="ClassEmpire/ClassColonizedStarSystem/PlanetTypeTerran"  SearchValueFromPath="true"  />

      <!-- Boreal, veldt, snow -2 happiness > +2 -->
      <BinaryModifier  TargetProperty="Happiness"  Operation="Addition" Left="4"   BinaryOperation="Multiplication" Right="$(MajorPopulationCount)"    Path="ClassEmpire/ClassColonizedStarSystem/PlanetTypeBoreal" SearchValueFromPath="true"  />
      <BinaryModifier  TargetProperty="Happiness"  Operation="Addition" Left="4"   BinaryOperation="Multiplication" Right="$(MajorPopulationCount)"    Path="ClassEmpire/ClassColonizedStarSystem/PlanetTypeVeldt"  SearchValueFromPath="true"  />
      <BinaryModifier  TargetProperty="Happiness"  Operation="Addition" Left="4"   BinaryOperation="Multiplication" Right="$(MajorPopulationCount)"    Path="ClassEmpire/ClassColonizedStarSystem/PlanetTypeSnow"   SearchValueFromPath="true"  />

      <!-- Ash, Arid, ice -5 happiness > +5 -->
      <BinaryModifier  TargetProperty="Happiness"  Operation="Addition" Left="10"  BinaryOperation="Multiplication" Right="$(MajorPopulationCount)"    Path="ClassEmpire/ClassColonizedStarSystem/PlanetTypeAsh"    SearchValueFromPath="true"  />
      <BinaryModifier  TargetProperty="Happiness"  Operation="Addition" Left="10"  BinaryOperation="Multiplication" Right="$(MajorPopulationCount)"    Path="ClassEmpire/ClassColonizedStarSystem/PlanetTypeArid"   SearchValueFromPath="true"  />
      <BinaryModifier  TargetProperty="Happiness"  Operation="Addition" Left="10"  BinaryOperation="Multiplication" Right="$(MajorPopulationCount)"    Path="ClassEmpire/ClassColonizedStarSystem/PlanetTypeIce"    SearchValueFromPath="true"  />
      
      <!-- Lava, Desert, Barren -8 happiness > +8 -->
      <BinaryModifier  TargetProperty="Happiness"  Operation="Addition" Left="16"  BinaryOperation="Multiplication" Right="$(MajorPopulationCount)"    Path="ClassEmpire/ClassColonizedStarSystem/PlanetTypeLava"   SearchValueFromPath="true"  />
      <BinaryModifier  TargetProperty="Happiness"  Operation="Addition" Left="16"  BinaryOperation="Multiplication" Right="$(MajorPopulationCount)"    Path="ClassEmpire/ClassColonizedStarSystem/PlanetTypeDesert" SearchValueFromPath="true"  />
      <BinaryModifier  TargetProperty="Happiness"  Operation="Addition" Left="16"  BinaryOperation="Multiplication" Right="$(MajorPopulationCount)"    Path="ClassEmpire/ClassColonizedStarSystem/PlanetTypeBarren" SearchValueFromPath="true"  />

      <!-- Gas -12 happiness > +5 -->
      <BinaryModifier  TargetProperty="Happiness"  Operation="Addition" Left="17"  BinaryOperation="Multiplication" Right="$(MajorPopulationCount)"    Path="ClassEmpire/ClassColonizedStarSystem/PlanetGameplayTypeGas" SearchValueFromPath="true"  />

    <!--<BinaryModifier     TargetProperty="Happiness"          Operation="Addition" Left="2"  BinaryOperation="Multiplication" Right="$(Population)"    Path="ClassEmpire/ClassColonizedStarSystem/PlanetGameplayTypeMeager" SearchValueFromPath="true"  />-->
    <!--<BinaryModifier     TargetProperty="Happiness"          Operation="Addition" Left="-2" BinaryOperation="Multiplication" Right="$(Population)"    Path="ClassEmpire/ClassColonizedStarSystem/PlanetGameplayTypeTeeming" SearchValueFromPath="true"  />-->
    </SimulationDescriptor>

    <!--Ship Cost Price of Perfection-->
    <SimulationDescriptor Name="FactionTraitPriceOfPerfection1"    Type="FactionTrait">
      <Modifier TargetProperty="ShipProductionCostReduction"	Operation="Addition" Value="0.10" Path="ClassEmpire/ClassColonizedStarSystem" Priority="-5"/>
      <Modifier TargetProperty="ColonyShipProductionCostReduction" Operation="Addition" Value="0.10" Path="ClassEmpire/ClassColonizedStarSystem" Priority="-5" TooltipHidden="true"/>
   
      <Modifier TargetProperty="Damage" Operation="Percent" Value="0.05" Path="ClassEmpire/ClassGarrison/ClassShip/ClassSection/ClassModule,ClassModuleWeapon"/>
    </SimulationDescriptor>
   
    <SimulationDescriptor Name="FactionTraitPriceOfPerfection2"    Type="FactionTrait">
      <Modifier TargetProperty="ShipProductionCostReduction"	Operation="Addition" Value="0.20" Path="ClassEmpire/ClassColonizedStarSystem" Priority="-5"/>
      <Modifier TargetProperty="ColonyShipProductionCostReduction" Operation="Addition" Value="0.20" Path="ClassEmpire/ClassColonizedStarSystem" Priority="-5" TooltipHidden="true"/>

      <Modifier TargetProperty="Damage" Operation="Percent" Value="0.10" Path="ClassEmpire/ClassGarrison/ClassShip/ClassSection/ClassModule,ClassModuleWeapon"/>
    </SimulationDescriptor>
	
</Datatable>
