=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Schemas/GroundBattleStrategyDefinition.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Datatable" />
  <xs:element name="GroundBattleStrategyDefinition" nillable="true" type="GroundBattleStrategyDefinition" />
  <xs:complexType name="GroundBattleStrategyDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="DatatableElement">
        <xs:sequence>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element minOccurs="0" maxOccurs="1" name="DatePrerequisite" type="DatePrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="GameSettingPrerequisite" type="GameSettingPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="TechnologyPrerequisite" type="TechnologyPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="PathPrerequisite" type="PathPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="InterpreterPrerequisite" type="InterpreterPrerequisite" />
          </xs:choice>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="SimulationDescriptorReference" type="SimulationDescriptorReference" />
          <xs:element minOccurs="0" maxOccurs="unbounded" name="InvasionEffect" type="InvasionEffect" />
        </xs:sequence>
        <xs:attribute name="Opponent" type="GroundBattleOpponent" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DatePrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="Prerequisite">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute default="false" name="Inverted" type="xs:boolean" />
        <xs:attribute name="Flags" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="GameSettingPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="PathValidityPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="TechnologyPrerequisite">
    <xs:simpleContent>
      <xs:extension base="PathValidityPrerequisite">
        <xs:attribute default="false" name="UnlockHidden" type="xs:boolean" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="PathPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="InterpreterPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="SimulationDescriptorReference">
    <xs:complexContent mixed="false">
      <xs:extension base="ValueType">
        <xs:attribute name="Name" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ValueType" />
  <xs:complexType name="InvasionEffect">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="SimulationDescriptorReference" type="SimulationDescriptorReference" />
    </xs:sequence>
    <xs:attribute name="Opponent" type="GroundBattleOpponent" use="required" />
  </xs:complexType>
  <xs:simpleType name="GroundBattleOpponent">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Attacker" />
      <xs:enumeration value="Defender" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="DatatableElement">
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
</xs:schema>

=== AdrianLopezIglesias/EnhancedSpace-Adaptation/GroundBattle/GroundBattleStrategies.xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Schemas/GroundBattleStrategyDefinition.xsd">

    <!-- Context:
    - AttackerEmpire: access to ClassEmpire of the Displayed Attacking empire
    - AttackerLostSystem: access to ClassStarSystem if the attacker still has ownership on it.
    - DefenderEmpire:  access to ClassEmpire of the Defender empire
    - DefenderSystem: access to ClassStarSystem of the Defender empire-->
  
  
    <!-- ########################-->
    <!--   MAJOR FACTION OPTIONS -->
    <!-- ########################-->


    <GroundBattleStrategyDefinition Name="GroundBattleAttackerStrategy3" Opponent="Attacker">
      <PathPrerequisite Flags="Discard">../ClassEmpire,EmpireTypeMajor</PathPrerequisite>
      <PathPrerequisite Flags="Discard">../ClassEmpire,!EmpireTypeMajor</PathPrerequisite>
    </GroundBattleStrategyDefinition>
    <GroundBattleStrategyDefinition Name="GroundBattleDefenderStrategy3" Opponent="Defender">
      <PathPrerequisite Flags="Discard">../ClassEmpire,EmpireTypeMajor</PathPrerequisite>
      <PathPrerequisite Flags="Discard">../ClassEmpire,!EmpireTypeMajor</PathPrerequisite>
    </GroundBattleStrategyDefinition>
    <GroundBattleStrategyDefinition Name="GroundBattleDefenderStrategy3Bhagabas" Opponent="Defender">
      <PathPrerequisite Flags="Discard">../ClassEmpire,EmpireTypeMajor</PathPrerequisite>
      <PathPrerequisite Flags="Discard">../ClassEmpire,!EmpireTypeMajor</PathPrerequisite>
    </GroundBattleStrategyDefinition>
  
    <!-- ########################-->
    <!--          OFFENCE        -->
    <!-- ########################-->
        
    <!-- Infiltration -->
  
    <GroundBattleStrategyDefinition Name="GroundBattleAttackerStrategy1" Opponent="Attacker">
        <PathPrerequisite Flags="Discard">../ClassEmpire,EmpireTypeMajor</PathPrerequisite>
        <SimulationDescriptorReference Name="GroundBattleAttackerStrategy1"/>
    </GroundBattleStrategyDefinition>
    
    <!-- Armored spearhead -->
    <GroundBattleStrategyDefinition Name="GroundBattleAttackerStrategy2" Opponent="Attacker">
        <PathPrerequisite Flags="Discard">../ClassEmpire,EmpireTypeMajor</PathPrerequisite>
		    <PathPrerequisite Flags="Discard" Inverted="true">../ClassEmpire,EmpireTypeMajor/ClassPopulationEmpire,PopulationCollectionBonusTikanans3</PathPrerequisite>
        <SimulationDescriptorReference  Name="GroundBattleAttackerStrategy2"/>
    </GroundBattleStrategyDefinition>
  
	  <GroundBattleStrategyDefinition Name="GroundBattleAttackerStrategy2Tikanans" Opponent="Attacker">
		  <PathPrerequisite Flags="Discard">../ClassEmpire,EmpireTypeMajor/ClassPopulationEmpire,PopulationCollectionBonusTikanans3</PathPrerequisite>
		  <SimulationDescriptorReference  Name="GroundBattleAttackerStrategy2Tikanans"/>
	  </GroundBattleStrategyDefinition>

    <!-- Carpet bombing --> 

    <GroundBattleStrategyDefinition Name="GroundBattleAttackerStrategy4" Opponent="Attacker">
      <PathPrerequisite Flags="Discard">../ClassEmpire,EmpireTypeMajor/ClassPopulationEmpire</PathPrerequisite>
      <SimulationDescriptorReference  Name="GroundBattleAttackerStrategy4"/>
    </GroundBattleStrategyDefinition>

    <!-- Orbital bombardment -->
    <GroundBattleStrategyDefinition Name="GroundBattleAttackerStrategy3_1" Opponent="Attacker">
      <PathPrerequisite Flags="Discard">../ClassEmpire,EmpireTypeMajor</PathPrerequisite>
      <InterpreterPrerequisite Flags="Disable,NotEnoughSiegePower">Property(DefenderSystem, @ClassColonizedStarSystem, OrbitingSiegePower, true) ge 80</InterpreterPrerequisite>
      <InterpreterPrerequisite Flags="Discard">Property(DefenderSystem, @ClassColonizedStarSystem, OrbitingSiegePower, true) lt 300</InterpreterPrerequisite>
      <SimulationDescriptorReference Name="GroundBattleAttackerStrategy3_1"/>
    </GroundBattleStrategyDefinition>

    <GroundBattleStrategyDefinition Name="GroundBattleAttackerStrategy3_2" Opponent="Attacker">
      <PathPrerequisite Flags="Discard">../ClassEmpire,EmpireTypeMajor</PathPrerequisite>
      <InterpreterPrerequisite Flags="Discard">Property(DefenderSystem, @ClassColonizedStarSystem, OrbitingSiegePower, true) ge 300</InterpreterPrerequisite>
      <InterpreterPrerequisite Flags="Discard">Property(DefenderSystem, @ClassColonizedStarSystem, OrbitingSiegePower, true) lt 600</InterpreterPrerequisite>
      <SimulationDescriptorReference Name="GroundBattleAttackerStrategy3_2"/>
    </GroundBattleStrategyDefinition>

    <GroundBattleStrategyDefinition Name="GroundBattleAttackerStrategy3_3" Opponent="Attacker">
      <PathPrerequisite Flags="Discard">../ClassEmpire,EmpireTypeMajor</PathPrerequisite>
      <InterpreterPrerequisite Flags="Discard">Property(DefenderSystem, @ClassColonizedStarSystem, OrbitingSiegePower, true) ge 600</InterpreterPrerequisite>
      <SimulationDescriptorReference Name="GroundBattleAttackerStrategy3_3"/>
    </GroundBattleStrategyDefinition>
  
  
  
    <!-- ########################-->
    <!--           DEFENCE       -->
    <!-- ########################-->

    <!-- Draft > Guerilla tactics -->

    <GroundBattleStrategyDefinition Name="GroundBattleDefenderStrategy1" Opponent="Defender">
        <PathPrerequisite Flags="Discard">../ClassEmpire,EmpireTypeMajor</PathPrerequisite>
        <InterpreterPrerequisite Flags="Disable,NoPopulationOnSystem">Property(DefenderSystem, @ClassColonizedStarSystem, Population) gt 1</InterpreterPrerequisite>
        <PathPrerequisite Flags="Discard" Inverted="true">../ClassEmpire,EmpireImprovementQuestUnitedEmpire11</PathPrerequisite>
        <PathPrerequisite Flags="GroundBattlePlaysHacked" Inverted="true">../ClassEmpire,TemporaryEffectGroundBattlePlaysHacked</PathPrerequisite>
        <SimulationDescriptorReference Name="GroundBattleDefenderStrategy1"/>
    </GroundBattleStrategyDefinition>

    <GroundBattleStrategyDefinition Name="GroundBattleDefenderStrategy1Terrans" Opponent="Defender">
        <PathPrerequisite Flags="Discard">../ClassEmpire,EmpireTypeMajor</PathPrerequisite>
        <InterpreterPrerequisite Flags="Disable,NoPopulationOnSystem">Property(DefenderSystem, @ClassColonizedStarSystem, Population) gt 1</InterpreterPrerequisite>
        <PathPrerequisite Flags="Discard">../ClassEmpire,EmpireImprovementQuestUnitedEmpire11</PathPrerequisite>
        <PathPrerequisite Flags="GroundBattlePlaysHacked" Inverted="true">../ClassEmpire,TemporaryEffectGroundBattlePlaysHacked</PathPrerequisite>
        <SimulationDescriptorReference Name="GroundBattleDefenderStrategy1Terrans"/>
    </GroundBattleStrategyDefinition>
  
    <!-- Defend system / Combined arms -->

    <GroundBattleStrategyDefinition Name="GroundBattleDefenderStrategy2" Opponent="Defender">
        <PathPrerequisite Flags="Discard">../ClassEmpire,EmpireTypeMajor</PathPrerequisite>
		  <PathPrerequisite Flags="Discard" Inverted="true">../ClassEmpire,EmpireTypeMajor/ClassPopulationEmpire,PopulationCollectionBonusGnashasts3</PathPrerequisite>
        <PathPrerequisite Flags="GroundBattlePlaysHacked" Inverted="true">../ClassEmpire,TemporaryEffectGroundBattlePlaysHacked</PathPrerequisite>
        <SimulationDescriptorReference Name="GroundBattleDefenderStrategy2"/>
    </GroundBattleStrategyDefinition>
	
	  <GroundBattleStrategyDefinition Name="GroundBattleDefenderStrategy2Gnashasts" Opponent="Defender">
		  <PathPrerequisite Flags="Discard">../ClassEmpire,EmpireTypeMajor/ClassPopulationEmpire,PopulationCollectionBonusGnashasts3</PathPrerequisite>
        <PathPrerequisite Flags="GroundBattlePlaysHacked" Inverted="true">../ClassEmpire,TemporaryEffectGroundBattlePlaysHacked</PathPrerequisite>
		  <SimulationDescriptorReference Name="GroundBattleDefenderStrategy2Gnashasts"/>
	  </GroundBattleStrategyDefinition>

    <!-- Indirect fire support --> 
  
    <GroundBattleStrategyDefinition Name="GroundBattleDefenderStrategy4" Opponent="Defender">
        <PathPrerequisite Flags="Discard">../ClassEmpire,EmpireTypeMajor</PathPrerequisite>
        <PathPrerequisite Flags="GroundBattlePlaysHacked" Inverted="true">../ClassEmpire,TemporaryEffectGroundBattlePlaysHacked</PathPrerequisite>
        <SimulationDescriptorReference Name="GroundBattleDefenderStrategy4"/>
    </GroundBattleStrategyDefinition>
    
    <!-- SURRENDER -->

    <GroundBattleStrategyDefinition Name="GroundBattleDefenderStrategy3B" Opponent="Defender">
        <PathPrerequisite Flags="Discard">../ClassEmpire,EmpireTypeMajor</PathPrerequisite>
		  <PathPrerequisite Flags="Discard" Inverted="true">../ClassEmpire,EmpireTypeMajor/ClassPopulationEmpire,PopulationCollectionBonusBhagabas3</PathPrerequisite>
        <PathPrerequisite Flags="GroundBattlePlaysHacked" Inverted="true">../ClassEmpire,TemporaryEffectGroundBattlePlaysHacked</PathPrerequisite>
        <SimulationDescriptorReference Name="GroundBattleDefenderStrategy3B"/> 
        <InvasionEffect Opponent="Attacker">
            <SimulationDescriptorReference Name="InvasionEffectSurrenderAttacker"/>
        </InvasionEffect>
        <InvasionEffect Opponent="Defender">
            <SimulationDescriptorReference Name="InvasionEffectSurrenderDefender"/>
        </InvasionEffect>
    </GroundBattleStrategyDefinition>
	
	  <GroundBattleStrategyDefinition Name="GroundBattleDefenderStrategy3BBhagabas" Opponent="Defender">
		  <PathPrerequisite Flags="Discard">../ClassEmpire,EmpireTypeMajor/ClassPopulationEmpire,PopulationCollectionBonusBhagabas3</PathPrerequisite>
        <PathPrerequisite Flags="GroundBattlePlaysHacked" Inverted="true">../ClassEmpire,TemporaryEffectGroundBattlePlaysHacked</PathPrerequisite>
		  <SimulationDescriptorReference Name="GroundBattleDefenderStrategy3BBhagabas"/>
        
          <InvasionEffect Opponent="Attacker">
