=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Schemas/HeroSkillTreeDefinition.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Datatable" />
  <xs:element name="HeroSkillTreeDefinition" nillable="true" type="HeroSkillTreeDefinition" />
  <xs:complexType name="HeroSkillTreeDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="DatatableElement">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="Stage" type="HeroSkillTreeStage" />
          <xs:element minOccurs="0" maxOccurs="1" name="Specializations" type="HeroSkillTreeStage" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="HeroSkillTreeStage">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Skill" type="HeroSkillTreeSkill" />
    </xs:sequence>
    <xs:attribute name="Level" type="xs:int" use="required" />
  </xs:complexType>
  <xs:complexType name="HeroSkillTreeSkill">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="SkillDefinition" type="XmlNamedReference" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Alternative" type="HeroSkillTreeSkill" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="RequiredSkill" type="XmlNamedReference" />
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="1" name="DatePrerequisite" type="DatePrerequisite" />
        <xs:element minOccurs="0" maxOccurs="1" name="GameSettingPrerequisite" type="GameSettingPrerequisite" />
        <xs:element minOccurs="0" maxOccurs="1" name="TechnologyPrerequisite" type="TechnologyPrerequisite" />
        <xs:element minOccurs="0" maxOccurs="1" name="InterpreterPrerequisite" type="InterpreterPrerequisite" />
        <xs:element minOccurs="0" maxOccurs="1" name="PathPrerequisite" type="PathPrerequisite" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="XmlNamedReference">
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="DatePrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="Prerequisite">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute default="false" name="Inverted" type="xs:boolean" />
        <xs:attribute name="Flags" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="GameSettingPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="PathValidityPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="TechnologyPrerequisite">
    <xs:simpleContent>
      <xs:extension base="PathValidityPrerequisite">
        <xs:attribute default="false" name="UnlockHidden" type="xs:boolean" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="InterpreterPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="PathPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="DatatableElement">
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
</xs:schema>

=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Simulation/HeroSkillTreeDefinitions[DLC2].xml
<?xml version="1.0" encoding="utf-8"?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Schemas/HeroSkillTreeDefinition.xsd">
    <!--MajorHisshos TREE-->
    <HeroSkillTreeDefinition Name="HeroSkillTreeMajorHisshos">
        <Stage Level="0">
            <Skill>
                <SkillDefinition Name="HeroSkill01BranchMajorHisshos"/>
            </Skill>
            <Skill>
                <SkillDefinition Name="HeroSkill02BranchMajorHisshos"/>
            </Skill>
        </Stage>
        <Stage Level="3">
            <Skill>
                <SkillDefinition Name="HeroSkill03BranchMajorHisshos"/>
                <RequiredSkill Name="HeroSkill01BranchMajorHisshos"/>
            </Skill>
            <Skill>
                <SkillDefinition Name="HeroSkill04BranchMajorHisshos"/>
                <RequiredSkill Name="HeroSkill02BranchMajorHisshos"/>
            </Skill>
        </Stage>
        <Stage Level="6">
            <Skill>
                <SkillDefinition Name="HeroSkill05BranchMajorHisshos"/>
                <RequiredSkill Name="HeroSkill03BranchMajorHisshos"/>
            </Skill>
            <Skill>
                <SkillDefinition Name="HeroSkill06BranchMajorHisshos"/>
                <RequiredSkill Name="HeroSkill04BranchMajorHisshos"/>
            </Skill>
        </Stage>
        <Stage Level="9">
            <Skill>
                <SkillDefinition Name="HeroSkill07BranchMajorHisshos"/>
                <RequiredSkill Name="HeroSkill05BranchMajorHisshos"/>
                <RequiredSkill Name="HeroSkill06BranchMajorHisshos"/>
            </Skill>
        </Stage>
    </HeroSkillTreeDefinition>
</Datatable>

=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Simulation/HeroSkillTreeDefinitions[DLC1].xml
<?xml version="1.0" encoding="utf-8"?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Schemas/HeroSkillTreeDefinition.xsd">
    <!--Vaulters TREE-->
    <HeroSkillTreeDefinition Name="HeroSkillTreeVaulters">
        <Stage Level="0">
            <Skill>
                <SkillDefinition Name="HeroSkill01BranchVaulters"/>
            </Skill>
            <Skill>
                <SkillDefinition Name="HeroSkill02BranchVaulters"/>
            </Skill>
        </Stage>
        <Stage Level="3">
            <Skill>
                <SkillDefinition Name="HeroSkill03BranchVaulters"/>
              <RequiredSkill Name="HeroSkill01BranchVaulters"/>
            </Skill>
            <Skill>
                <SkillDefinition Name="HeroSkill04BranchVaulters"/>
                <RequiredSkill Name="HeroSkill02BranchVaulters"/>
            </Skill>
        </Stage>
        <Stage Level="6">
            <Skill>
                <SkillDefinition Name="HeroSkill05BranchVaulters"/>
                <RequiredSkill Name="HeroSkill03BranchVaulters"/>
            </Skill>
            <Skill>
                <SkillDefinition Name="HeroSkill06BranchVaulters"/>
                <RequiredSkill Name="HeroSkill04BranchVaulters"/>
            </Skill>
        </Stage>
        <Stage Level="9">
            <Skill>
                <SkillDefinition Name="HeroSkill07BranchVaulters"/>
                <RequiredSkill Name="HeroSkill05BranchVaulters"/>
                <RequiredSkill Name="HeroSkill06BranchVaulters"/>
            </Skill>
        </Stage>
    </HeroSkillTreeDefinition>
</Datatable>
