=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Schemas/LawDefinition.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Datatable" />
  <xs:element name="LawDefinition" nillable="true" type="LawDefinition" />
  <xs:complexType name="LawDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="UnlockDatatableElement">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="AIGain" type="AIGain" />
          <xs:element minOccurs="0" maxOccurs="1" name="Politics" type="XmlNamedReference" />
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element minOccurs="0" maxOccurs="1" name="CustomCost" type="CustomConstructionCost" />
            <xs:element minOccurs="0" maxOccurs="1" name="Cost" type="ConstructionCost" />
          </xs:choice>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element minOccurs="0" maxOccurs="1" name="LawEffectTransferResources" type="LawEffectTransferResources" />
            <xs:element minOccurs="0" maxOccurs="1" name="LawEffectSimulation" type="LawEffectSimulation" />
          </xs:choice>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element minOccurs="0" maxOccurs="1" name="DatePrerequisite" type="DatePrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="GameSettingPrerequisite" type="GameSettingPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="SupportPrerequisite" type="SupportPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="PoliticsExperiencePrerequisite" type="PoliticsExperiencePrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="TechnologyPrerequisite" type="TechnologyPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="InterpreterPrerequisite" type="InterpreterPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="PathPrerequisite" type="PathPrerequisite" />
          </xs:choice>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="CostReductionReference" type="CostReductionReference" />
          <xs:element minOccurs="0" maxOccurs="unbounded" name="SimulationDescriptorReference" type="SimulationDescriptorReference" />
          <xs:element minOccurs="0" maxOccurs="unbounded" name="BattleActionReference" type="XmlNamedReference" />
        </xs:sequence>
        <xs:attribute default="false" name="Forced" type="xs:boolean" />
        <xs:attribute default="false" name="IsQuestRelated" type="xs:boolean" />
        <xs:attribute default="0" name="Duration" type="xs:int" />
        <xs:attribute default="false" name="IsVolatile" type="xs:boolean" />
        <xs:attribute default="false" name="NoCancel" type="xs:boolean" />
        <xs:attribute name="SubCategory" type="xs:string" />
        <xs:attribute name="ScoreProvider" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="AIGain">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Tag" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="RessourceName" type="xs:string" />
    <xs:attribute default="false" name="Inverted" type="xs:boolean" />
  </xs:complexType>
  <xs:complexType name="XmlNamedReference">
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="CustomConstructionCost">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute default="false" name="Instant" type="xs:boolean" />
        <xs:attribute default="false" name="InstantOnCompletion" type="xs:boolean" />
        <xs:attribute name="ResourceName" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ConstructionCost">
    <xs:simpleContent>
      <xs:extension base="xs:float">
        <xs:attribute default="false" name="Instant" type="xs:boolean" />
        <xs:attribute default="false" name="InstantOnCompletion" type="xs:boolean" />
        <xs:attribute name="ResourceName" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="LawEffectTransferResources">
    <xs:complexContent mixed="false">
      <xs:extension base="LawEffect">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="TransferResource" type="TransferResource" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="TransferResource">
    <xs:complexContent mixed="false">
      <xs:extension base="ValueType">
        <xs:attribute name="Name" type="xs:string" />
        <xs:attribute name="Amount" type="xs:float" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ValueType" />
  <xs:complexType name="SimulationDescriptorReference">
    <xs:complexContent mixed="false">
      <xs:extension base="ValueType">
        <xs:attribute name="Name" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="LawEffect" />
  <xs:complexType name="LawEffectSimulation">
    <xs:complexContent mixed="false">
      <xs:extension base="LawEffect">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="SimulationDescriptorReference" type="SimulationDescriptorReference" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DatePrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="Prerequisite">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute default="false" name="Inverted" type="xs:boolean" />
        <xs:attribute name="Flags" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="GameSettingPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="SupportPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite">
        <xs:attribute name="Politics" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="PoliticsExperiencePrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite">
        <xs:attribute name="Politics" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="PathValidityPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="TechnologyPrerequisite">
    <xs:simpleContent>
      <xs:extension base="PathValidityPrerequisite">
        <xs:attribute default="false" name="UnlockHidden" type="xs:boolean" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="InterpreterPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="PathPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="CostReductionReference">
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="UnlockDatatableElement">
    <xs:complexContent mixed="false">
      <xs:extension base="DatatableElement">
        <xs:attribute name="KeyWords" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DatatableElement">
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
</xs:schema>

=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Simulation/LawDefinitions[DLC3].xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Schemas/LawDefinition.xsd">



   <!-- removed -->
   <LawDefinition Name="LawP01L01UmbralChoir" SubCategory="LawPolitics04" ScoreProvider="EcologistLawEnacted" Duration="1" >
        <Politics Name="Politics04"/>
       <CustomCost ResourceName="EmpireEmpirePoint">Max(Round(Property(Context,@'../ClassEmpire/ClassSenate',LawActivationCostModifier) * 5),Round(Property(Context,@'../ClassEmpire/ClassSenate',LawActivationCostModifier) * (.2*Property(Context,@'../ClassEmpire',NetEmpireEmpirePoint))))</CustomCost>
        <LawEffectSimulation>
            <SimulationDescriptorReference Name="LawEffectP01L01UmbralChoir" />
        </LawEffectSimulation>
      <PathPrerequisite Flags="Prerequisite,Discard,Faction">../ClassEmpire,AffinityGameplayUmbralChoir</PathPrerequisite>
      <PathPrerequisite Flags="Prerequisite,Discard,Faction">../ClassEmpire,!AffinityGameplayUmbralChoir</PathPrerequisite>
        <PathPrerequisite Flags="Prerequisite,Discard,Government">ClassSenate,!GovernmentRepublic</PathPrerequisite>
        <PathPrerequisite Flags="Prerequisite,Discard" Inverted="true">../ClassEmpire,FactionTraitManualHomeSystem</PathPrerequisite>
        <SupportPrerequisite Flags="Prerequisite,Disable,Support" Politics="Politics04">1</SupportPrerequisite>
        <InterpreterPrerequisite Flags="Prerequisite,AdditionalUpkeep">(Property(Context,@'../ClassEmpire',NetEmpireEmpirePoint) + Property(Context,@'../ClassEmpire',EmpireEmpirePointStock)) ge 2 * Property(Context, @'../ClassEmpire', Population)</InterpreterPrerequisite>
        <PoliticsExperiencePrerequisite Flags="Prerequisite,Disable,Experience" Politics="Politics04">0</PoliticsExperiencePrerequisite>
        <SimulationDescriptorReference Name="LawPolitics04"/>
        <SimulationDescriptorReference Name="LawUpkeepLevel1"/>
    </LawDefinition>

   <!-- removed -->  
    <LawDefinition Name="LawP01L01UmbralChoirRepublic" SubCategory="LawPolitics04" ScoreProvider="EcologistLawEnacted" Duration="1" >
        <Politics Name="Politics04"/>
        <CustomCost ResourceName="EmpireEmpirePoint">Max(Round(Property(Context,@'../ClassEmpire/ClassSenate',LawActivationCostModifier) * 5),Round(Property(Context,@'../ClassEmpire/ClassSenate',LawActivationCostModifier) * (.2*Property(Context,@'../ClassEmpire',NetEmpireEmpirePoint))))</CustomCost>
        <LawEffectSimulation>
            <SimulationDescriptorReference Name="LawEffectP01L01UmbralChoirRepublic" />
        </LawEffectSimulation>
       <PathPrerequisite Flags="Prerequisite,Discard,Faction">../ClassEmpire,AffinityGameplayUmbralChoir</PathPrerequisite>
       <PathPrerequisite Flags="Prerequisite,Discard,Faction">../ClassEmpire,!AffinityGameplayUmbralChoir</PathPrerequisite>
        <PathPrerequisite Flags="Prerequisite,Discard,Government">ClassSenate,GovernmentRepublic</PathPrerequisite>
        <PathPrerequisite Flags="Prerequisite,Discard" Inverted="true">../ClassEmpire,FactionTraitManualHomeSystem</PathPrerequisite>
        <SupportPrerequisite Flags="Prerequisite,Disable,Support" Politics="Politics04">1</SupportPrerequisite>
        <InterpreterPrerequisite Flags="Prerequisite,AdditionalUpkeep">(Property(Context,@'../ClassEmpire',NetEmpireEmpirePoint) + Property(Context,@'../ClassEmpire',EmpireEmpirePointStock)) ge 2 * Property(Context, @'../ClassEmpire', Population)</InterpreterPrerequisite>
        <PoliticsExperiencePrerequisite Flags="Prerequisite,Disable,Experience" Politics="Politics04">0</PoliticsExperiencePrerequisite>
        <SimulationDescriptorReference Name="LawPolitics04"/>
        <SimulationDescriptorReference Name="LawUpkeepLevel1"/>
    </LawDefinition>

   <LawDefinition Name="LawP04L01UmbralChoir" SubCategory="LawPolitics04" ScoreProvider="EcologistLawEnacted" Duration="1" >
      <Politics Name="Politics04"/>
      <CustomCost ResourceName="EmpireEmpirePoint">Max(Round(Property(Context,@'../ClassEmpire/ClassSenate',LawActivationCostModifier) * 5),Round(Property(Context,@'../ClassEmpire/ClassSenate',LawActivationCostModifier) * (.2*Property(Context,@'../ClassEmpire',NetEmpireEmpirePoint))))</CustomCost>
      <LawEffectSimulation>
         <SimulationDescriptorReference Name="LawEffectP01L01UmbralChoir" />
      </LawEffectSimulation>
      <PathPrerequisite Flags="Prerequisite,Discard,Faction">../ClassEmpire,AffinityGameplayUmbralChoir</PathPrerequisite>
      <PathPrerequisite Flags="Prerequisite,Discard,Government">ClassSenate,!GovernmentRepublic</PathPrerequisite>
      <PathPrerequisite Flags="Prerequisite,Discard" Inverted="true">../ClassEmpire,FactionTraitManualHomeSystem</PathPrerequisite>
      <SupportPrerequisite Flags="Prerequisite,Disable,Support" Politics="Politics04">1</SupportPrerequisite>
      <InterpreterPrerequisite Flags="Prerequisite,AdditionalUpkeep">(Property(Context,@'../ClassEmpire',NetEmpireEmpirePoint) + Property(Context,@'../ClassEmpire',EmpireEmpirePointStock)) ge 2 * Property(Context, @'../ClassEmpire', Population)</InterpreterPrerequisite>
      <PoliticsExperiencePrerequisite Flags="Prerequisite,Disable,Experience" Politics="Politics04">0</PoliticsExperiencePrerequisite>
      <SimulationDescriptorReference Name="LawPolitics04"/>
      <SimulationDescriptorReference Name="LawUpkeepLevel1"/>
   </LawDefinition>

   <LawDefinition Name="LawP04L01UmbralChoirRepublic" SubCategory="LawPolitics04" ScoreProvider="EcologistLawEnacted" Duration="1" >
      <Politics Name="Politics04"/>
      <CustomCost ResourceName="EmpireEmpirePoint">Max(Round(Property(Context,@'../ClassEmpire/ClassSenate',LawActivationCostModifier) * 5),Round(Property(Context,@'../ClassEmpire/ClassSenate',LawActivationCostModifier) * (.2*Property(Context,@'../ClassEmpire',NetEmpireEmpirePoint))))</CustomCost>
      <LawEffectSimulation>
         <SimulationDescriptorReference Name="LawEffectP01L01UmbralChoirRepublic" />
      </LawEffectSimulation>
      <PathPrerequisite Flags="Prerequisite,Discard,Faction">../ClassEmpire,AffinityGameplayUmbralChoir</PathPrerequisite>
      <PathPrerequisite Flags="Prerequisite,Discard,Government">ClassSenate,GovernmentRepublic</PathPrerequisite>
      <PathPrerequisite Flags="Prerequisite,Discard" Inverted="true">../ClassEmpire,FactionTraitManualHomeSystem</PathPrerequisite>
      <SupportPrerequisite Flags="Prerequisite,Disable,Support" Politics="Politics04">1</SupportPrerequisite>
      <InterpreterPrerequisite Flags="Prerequisite,AdditionalUpkeep">(Property(Context,@'../ClassEmpire',NetEmpireEmpirePoint) + Property(Context,@'../ClassEmpire',EmpireEmpirePointStock)) ge 2 * Property(Context, @'../ClassEmpire', Population)</InterpreterPrerequisite>
      <PoliticsExperiencePrerequisite Flags="Prerequisite,Disable,Experience" Politics="Politics04">0</PoliticsExperiencePrerequisite>
      <SimulationDescriptorReference Name="LawPolitics04"/>
      <SimulationDescriptorReference Name="LawUpkeepLevel1"/>
   </LawDefinition>
  

</Datatable>
