=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Schemas/PiratePowerLevelDefinition.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Datatable" />
  <xs:element name="PiratePowerLevelDefinition" nillable="true" type="PiratePowerLevelDefinition" />
  <xs:complexType name="PiratePowerLevelDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="DatatableElement">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="SimulationDescriptorReference" type="SimulationDescriptorReference" />
          <xs:element minOccurs="0" maxOccurs="unbounded" name="FleetSpawn" type="PirateFleetSpawn" />
          <xs:element minOccurs="0" maxOccurs="1" name="FleetMissionDefinitionReference" type="XmlNamedReference" />
          <xs:element minOccurs="0" maxOccurs="1" name="Droplist" type="PirateDroplist" />
        </xs:sequence>
        <xs:attribute name="PowerLevel" type="xs:int" use="required" />
        <xs:attribute name="Difficulty" type="xs:string" />
        <xs:attribute name="MinimumPowerPointsStock" type="xs:float" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SimulationDescriptorReference">
    <xs:complexContent mixed="false">
      <xs:extension base="ValueType">
        <xs:attribute name="Name" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ValueType" />
  <xs:complexType name="PirateFleetSpawn">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="ShipDesignReference" type="XmlNamedReference" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Reinforcement" type="PirateFleetReinforcement" />
    </xs:sequence>
    <xs:attribute default="1" name="Weight" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="XmlNamedReference">
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="PirateFleetReinforcement">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="ShipDesignReference" type="XmlNamedReference" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="SimulationDescriptorReference" type="SimulationDescriptorReference" />
    </xs:sequence>
    <xs:attribute name="Cost" type="xs:float" use="required" />
  </xs:complexType>
  <xs:complexType name="PirateDroplist">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="DroppableResource" type="DroppableResource" />
    </xs:sequence>
    <xs:attribute name="Picks" type="xs:int" use="required" />
  </xs:complexType>
  <xs:complexType name="DroppableResource">
    <xs:complexContent mixed="false">
      <xs:extension base="Droppable">
        <xs:attribute name="Quantity" type="xs:int" use="required" />
        <xs:attribute name="Name" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Droppable">
    <xs:attribute default="true" name="CanHaveDuplicate" type="xs:boolean" />
    <xs:attribute default="1" name="Weight" type="xs:int" />
    <xs:attribute default="0" name="MaxTurn" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="DatatableElement">
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
</xs:schema>

=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Simulation/PiratePowerLevelDefinitions.xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Schemas/PiratePowerLevelDefinition.xsd">

    <!-- Note: simulation descriptors are applied on the empire -->
    <!-- They are SWAPPED based on their type. They cannot be removed, they must be replaced with an empty one. -->


    <!--#####HOW-TO: REINFORCEMENTS#####
    ####################################
    Reinforcement descriptors are applied on the fleet directly, so the path can start on the ClassGarrison
    Reinforcements thresholds and effects are additive, which means that if the 1st and 2nd thresholds have a Cost="33" they will be placed at 33% and 66% on the bar.
    If they both have a bonus of +10% Health, having both thresholds will give a total of +20% Health. 
    Bar range is [0-100] so the sum of thresholds cannot exceed 100.
    Bonuses are given to a fleet. So don't forget to duplicate the bonus to all the alternative versions of a same fleet.
    
    <SimulationDescriptorReference Name="ABC123"/> to add a regular stats Bonus
    <ShipDesignReference Name="XYZ"/> to add a Bonus Ship
    Descriptors for bonuses are referenced in SimulationDescriptors[Pirates].xml
    Pirate Ships for both core Fleets and Reinforcements are defined in HullDefinitions[MinorFactions].xml-->
    

    <!-- None -->
    <PiratePowerLevelDefinition Name="PiratePowerLevelNone0" PowerLevel="0" Difficulty="None" MinimumPowerPointsStock="0">
        <SimulationDescriptorReference Name="DisabledPiratesEffect"/>
    </PiratePowerLevelDefinition>

    <!-- Medium (obsolete but needed for dev saves...) -->
    <PiratePowerLevelDefinition Name="PiratePowerLevelMedium0" PowerLevel="0" Difficulty="Medium" MinimumPowerPointsStock="0">
        <SimulationDescriptorReference Name="DisabledPiratesEffect"/>
    </PiratePowerLevelDefinition>


    <!-- ###EASY### -->
    <!-- No spawn -->
    <PiratePowerLevelDefinition Name="PiratePowerLevelEasy0" PowerLevel="0" Difficulty="Easy" MinimumPowerPointsStock="0">
        <SimulationDescriptorReference Name="PiratePowerLevel0Effect"/>
        <SimulationDescriptorReference Name="PirateDifficultyEasy"/>
        <FleetMissionDefinitionReference Name="RoamAndInvade"/>
    </PiratePowerLevelDefinition>

    <!-- EASY - PIRATE POWER 1 -->
    <PiratePowerLevelDefinition Name="PiratePowerLevelEasy1" PowerLevel="1" Difficulty="Easy" MinimumPowerPointsStock="25">
        <SimulationDescriptorReference Name="PiratePowerLevel1Effect"/>
        <SimulationDescriptorReference Name="PirateDifficultyEasy"/>
         
        <FleetSpawn Weight="1"> <!--Use Weight to list multiple fleet templates to choose between-->
            <ShipDesignReference Name="MFPiratesSmallAttackWeak"/>
             <Reinforcement Cost="33"><!--Reinforcements for this fleet template-->
                 <SimulationDescriptorReference Name="PirateReinforcementIncreasedSpeed01"/>
             </Reinforcement>
             <Reinforcement Cost="33">
                 <SimulationDescriptorReference Name="PirateReinforcementIncreasedHealth01"/>
             </Reinforcement>
             <Reinforcement Cost="33">
                 <SimulationDescriptorReference Name="PirateReinforcementIncreasedHealth01"/>
             </Reinforcement>
         </FleetSpawn>
        <FleetSpawn Weight="1">
            <ShipDesignReference Name="MFAdvancedSmallAttackWeak"/>
            <Reinforcement Cost="33">
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedSpeed01"/>
            </Reinforcement>
            <Reinforcement Cost="33">
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedHealth01"/>
            </Reinforcement>
            <Reinforcement Cost="33">
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedHealth01"/>
            </Reinforcement>
        </FleetSpawn>
        <FleetSpawn Weight="1">
            <ShipDesignReference Name="MFInsectoidSmallAttackWeak"/>
            <Reinforcement Cost="33">
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedSpeed01"/>
            </Reinforcement>
            <Reinforcement Cost="33">
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedHealth01"/>
            </Reinforcement>
            <Reinforcement Cost="33">
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedHealth01"/>
            </Reinforcement>
        </FleetSpawn>
        <FleetSpawn Weight="1">
            <ShipDesignReference Name="MFPrimitiveSmallAttackWeak"/>
            <Reinforcement Cost="33">
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedSpeed01"/>
            </Reinforcement>
            <Reinforcement Cost="33">
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedHealth01"/>
            </Reinforcement>
            <Reinforcement Cost="33">
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedHealth01"/>
            </Reinforcement>
        </FleetSpawn>

        <FleetMissionDefinitionReference Name="RoamAndInvade"/>
        
        <!--Loot awarded for destroying a Lair at PP1-->
        <Droplist Picks="1"> <!--Pick 1 item from the list-->
            <DroppableResource Name="EmpireMoney"    Quantity="300"  Weight="3"/> <!--300 * PiratePower-->
        </Droplist>
    </PiratePowerLevelDefinition>

    <!-- EASY - PIRATE POWER 2 -->
    <PiratePowerLevelDefinition Name="PiratePowerLevelEasy2" PowerLevel="2" Difficulty="Easy" MinimumPowerPointsStock="75">
        <SimulationDescriptorReference Name="PiratePowerLevel2Effect"/>
        <SimulationDescriptorReference Name="PirateDifficultyEasy"/>
        <FleetSpawn Weight="1">
            <ShipDesignReference Name="MFPiratesSmallAttackAvg"/>
            <Reinforcement Cost="33">
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedSpeed01"/>
                  <SimulationDescriptorReference Name="PirateReinforcementIncreasedHealth01"/>
              </Reinforcement>
            <Reinforcement Cost="33">
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedHealth01"/>
            </Reinforcement>
            <Reinforcement Cost="33">
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedHealth01"/>
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedDefense01"/>
            </Reinforcement>
        </FleetSpawn>
        <FleetSpawn Weight="1">
            <ShipDesignReference Name="MFAdvancedSmallAttackAvg"/>
            <Reinforcement Cost="33">
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedSpeed01"/>
                  <SimulationDescriptorReference Name="PirateReinforcementIncreasedHealth01"/>
              </Reinforcement>
            <Reinforcement Cost="33">
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedHealth01"/>
            </Reinforcement>
            <Reinforcement Cost="33">
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedHealth01"/>
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedDefense01"/>
            </Reinforcement>
        </FleetSpawn>
        <FleetSpawn Weight="1">
            <ShipDesignReference Name="MFInsectoidSmallAttackAvg"/>
            <Reinforcement Cost="33">
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedSpeed01"/>
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedHealth01"/>
            </Reinforcement>
            <Reinforcement Cost="33">
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedHealth01"/>
            </Reinforcement>
            <Reinforcement Cost="33">
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedHealth01"/>
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedDefense01"/>
            </Reinforcement>
        </FleetSpawn>
        <FleetSpawn Weight="1">
            <ShipDesignReference Name="MFPrimitiveSmallAttackAvg"/>
            <Reinforcement Cost="33">
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedSpeed01"/>
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedHealth01"/>
            </Reinforcement>
            <Reinforcement Cost="33">
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedHealth01"/>
            </Reinforcement>
            <Reinforcement Cost="33">
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedHealth01"/>
                <SimulationDescriptorReference Name="PirateReinforcementIncreasedDefense01"/>
            </Reinforcement>
        </FleetSpawn>
        
        <FleetMissionDefinitionReference Name="RoamAndInvade"/>

        <!--Loot awarded for destroying a Lair at PP2-->
        <Droplist Picks="1">
            <DroppableResource Name="EmpireMoney"    Quantity="600"  Weight="3"/> <!--300 * PiratePower-->
            <DroppableResource Name="Strategic1"     Quantity="20"   Weight="3"/> <!--10  * PiratePower-->
            <DroppableResource Name="Strategic2"     Quantity="20"   Weight="3"/> <!--10  * PiratePower-->
            
            <DroppableResource Name="Luxury1"        Quantity="20"   Weight="1"/> <!--10  * PiratePower-->
            <DroppableResource Name="Luxury2"        Quantity="20"   Weight="1"/>
            <DroppableResource Name="Luxury3"        Quantity="20"   Weight="1"/>
            <DroppableResource Name="Luxury4"        Quantity="20"   Weight="1"/>
            <DroppableResource Name="Luxury5"        Quantity="20"   Weight="1"/>
