=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Schemas/SystemSupervisorDefinition.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Datatable" />
  <xs:element name="SystemSupervisorDefinition" nillable="true" type="SystemSupervisorDefinition" />
  <xs:complexType name="SystemSupervisorDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="DatatableElement">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="1" name="Policy" type="SystemAutomatonPolicy" />
          <xs:element minOccurs="0" maxOccurs="1" name="Gains" type="ArrayOfSupervisorGain" />
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element minOccurs="0" maxOccurs="1" name="DatePrerequisite" type="DatePrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="GameSettingPrerequisite" type="GameSettingPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="DownloadableContentPrerequisite" type="DownloadableContentPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="SupportPrerequisite" type="SupportPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="TechnologyPrerequisite" type="TechnologyPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="InterpreterPrerequisite" type="InterpreterPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="PathPrerequisite" type="PathPrerequisite" />
          </xs:choice>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SystemAutomatonPolicy">
    <xs:attribute name="CanQueueConstructions" type="xs:boolean" use="required" />
    <xs:attribute name="CanMovePopulations" type="xs:boolean" use="required" />
  </xs:complexType>
  <xs:complexType name="ArrayOfSupervisorGain">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Gain" type="SupervisorGain" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SupervisorGain">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="Tags" type="Tags" />
    </xs:sequence>
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute default="1" name="Weight" type="xs:float" />
  </xs:complexType>
  <xs:complexType name="Tags">
    <xs:simpleContent>
      <xs:extension base="xs:string" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="DatePrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="Prerequisite">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute default="false" name="Inverted" type="xs:boolean" />
        <xs:attribute name="Flags" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="GameSettingPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="DownloadableContentPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="SupportPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite">
        <xs:attribute name="Politics" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="PathValidityPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="TechnologyPrerequisite">
    <xs:simpleContent>
      <xs:extension base="PathValidityPrerequisite">
        <xs:attribute default="false" name="UnlockHidden" type="xs:boolean" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="InterpreterPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="PathPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="DatatableElement">
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
</xs:schema>

=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Simulation/SystemSupervisorDefinitions.xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Schemas/SystemSupervisorDefinition.xsd">

    <!-- DEV NOTES:

            o  Weight(Constructible) = Sum(Constructible[Gain].Weight * Supervisor[Gain].Weight).
            o  Contextual constructibles (per planet, per population, on planetType) are only handled by altering the weights. 
            o  For recipes, gains should be descripbed in ingredients.

            o Weight(Planet,Pop) = Sum(Population[Gain/PlanetType].Weight * Supervisor[Gain].Weight) + Sum(Player[Fids].Net * Supervisor[Gain].Weight).
            o Population distribution:
              - First pass: Sort planets in weight descending order, and assign best population according to context.
              - Second pass: Move populations (worst) from overpopulated to free planets (best).
              - This is the simple explanation. the real one is to long to be described in here :3
              
            o GUI : Don't forget GuiElements ! Only supervisors that have a GuiElement specified in GuiElements[SystemSupervisors].xml will be displayed in the Supervisor Droplist.
    -->

    <!-- Balanced -->
    <SystemSupervisorDefinition Name="SystemSupervisorBalanced">
      <Policy CanQueueConstructions="true" CanMovePopulations="true"/>
      <Gains>
        <Gain Name="Food"      Weight="1.4"/>
        <Gain Name="Approval"  Weight="1.2"/>
        <Gain Name="Industry"  Weight="1.5"/>
        <Gain Name="Dust"      Weight="1"/>
        <Gain Name="Science"   Weight="1"/>
        <Gain Name="Prestige"  Weight="1"/>
        <Gain Name="Military"  Weight="0.4"/>
        <Gain Name="Planetary"  Weight="-10000"/>
      </Gains>
    </SystemSupervisorDefinition>
</Datatable>
