=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Schemas/TemporaryEffectDefinition.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Datatable" />
  <xs:element name="TemporaryEffectDefinition" nillable="true" type="TemporaryEffectDefinition" />
  <xs:complexType name="TemporaryEffectDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="DatatableElement">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="1" name="Path" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="unbounded" name="SimulationDescriptorReference" type="SimulationDescriptorReference" />
        </xs:sequence>
        <xs:attribute default="false" name="Silent" type="xs:boolean" />
        <xs:attribute name="Category" type="xs:string" />
        <xs:attribute name="SubCategory" type="xs:string" />
        <xs:attribute name="Duration" type="xs:int" use="required" />
        <xs:attribute default="false" name="StopOnWar" type="xs:boolean" />
        <xs:attribute default="true" name="Hidden" type="xs:boolean" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SimulationDescriptorReference">
    <xs:complexContent mixed="false">
      <xs:extension base="ValueType">
        <xs:attribute name="Name" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ValueType" />
  <xs:complexType name="DatatableElement">
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
  <xs:element name="TemporaryEffectMinorRelationDefinition" nillable="true" type="TemporaryEffectMinorRelationDefinition" />
  <xs:complexType name="TemporaryEffectMinorRelationDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="TemporaryEffectDefinition" />
    </xs:complexContent>
  </xs:complexType>
</xs:schema>

=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Simulation/TemporaryEffectDefinitions[DLC1].xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Schemas/TemporaryEffectDefinition.xsd">

  <TemporaryEffectDefinition Name="EmpirePointMalusFromDemand2" Category="EmpirePointMalusFromDemand" Duration="20">
    <Path>ClassEmpire,EmpireTypeMajor</Path>
    <SimulationDescriptorReference Name="EmpirePointMalusFromDemand2"/>
  </TemporaryEffectDefinition>
  
  <TemporaryEffectDefinition Name="FIDSMalusFromDemand2" Category="FIDSMalusFromDemand" Duration="20">
    <Path>ClassEmpire,EmpireTypeMajor</Path>
    <SimulationDescriptorReference Name="FIDSMalusFromDemand2"/>
  </TemporaryEffectDefinition>

  <TemporaryEffectDefinition Name="FleetUpkeepIncreaseFromDemand" Category="FleetUpkeepIncreaseFromDemand" Duration="20">
    <Path>ClassEmpire,EmpireTypeMajor</Path>
    <SimulationDescriptorReference Name="FleetUpkeepIncreaseFromDemand"/>
  </TemporaryEffectDefinition>

  <TemporaryEffectDefinition Name="MilitaryShipCostIncreaseFromDemand2" Category="MilitaryShipCostIncreaseFromDemand" Duration="20">
    <Path>ClassEmpire,EmpireTypeMajor</Path>
    <SimulationDescriptorReference Name="MilitaryShipCostIncreaseFromDemand2"/>
  </TemporaryEffectDefinition>

</Datatable>

=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Simulation/TemporaryEffectDefinitions.xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Schemas/TemporaryEffectDefinition.xsd">

    <!-- Gameplay -->
    <TemporaryEffectDefinition Name="ColonyHappinessBoost" Category="LawEffects" Duration="20">
        <Path>../ClassEmpire/ClassColonizedStarSystem</Path>
        <SimulationDescriptorReference Name="TemporaryEffectColonyHappinessBoost"/>
    </TemporaryEffectDefinition>
    
    <TemporaryEffectDefinition Name="StarSystemImprovementWonder1TemporaryEffect" Category="StarSystemImprovementWonder1" Duration="40">
        <Path>../ClassEmpire</Path>
        <SimulationDescriptorReference Name="TemporaryEffectStarSystemImprovementWonder1"/>
    </TemporaryEffectDefinition>

	<!-- Minor Relation -->
	<TemporaryEffectMinorRelationDefinition Name="MinorRelationWithMajorCuriosityRevealed" Category="MinorRelationWithMajor" Duration="1">
        <Path>ClassMinorRelationWithMajor</Path>
        <SimulationDescriptorReference Name="MinorRelationWithMajorCuriosityRevealed"/>
    </TemporaryEffectMinorRelationDefinition>

  <TemporaryEffectMinorRelationDefinition Name="MinorRelationWithMajorPraise" Category="MinorRelationWithMajor" Duration="10" StopOnWar="true">
    <Path>ClassMinorRelationWithMajor</Path>
    <SimulationDescriptorReference Name="MinorRelationWithMajorPraise"/>
  </TemporaryEffectMinorRelationDefinition>

  <TemporaryEffectDefinition Name="CreateMajorPopulationMemoryCounter" Category="Population" Duration="99999" >
    <Path>ClassColonizedStarSystem</Path>
    <SimulationDescriptorReference Name="TemporaryEffectCreateMajorPopulationMemoryCounter"/>
  </TemporaryEffectDefinition>

   <TemporaryEffectDefinition Name="StarSystemImprovementEnrollmentTempEffect" Category="Population" Duration="1" >
      <Path>ClassColonizedStarSystem</Path>
      <SimulationDescriptorReference Name="TemporaryEffectStarSystemImprovementEnrollment"/>
   </TemporaryEffectDefinition>

   <TemporaryEffectDefinition Name="StarSystemImprovementEnrollmentVampirilisTempEffect" Category="Population" Duration="1" >
      <Path>ClassColonizedStarSystem</Path>
      <SimulationDescriptorReference Name="TemporaryEffectStarSystemImprovementEnrollmentVampirilis"/>
   </TemporaryEffectDefinition>

   

</Datatable>
