=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Schemas/TradableDefinition.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Datatable" />
  <xs:element name="TradableDefinition" nillable="true" type="TradableDefinition" />
  <xs:complexType name="TradableDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="DatatableElement">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="1" name="BasePrice" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="unbounded" name="SimulationDescriptorReference" type="SimulationDescriptorReference" />
        </xs:sequence>
        <xs:attribute name="Category" type="xs:string" />
        <xs:attribute name="SubCategory" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SimulationDescriptorReference">
    <xs:complexContent mixed="false">
      <xs:extension base="ValueType">
        <xs:attribute name="Name" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ValueType" />
  <xs:complexType name="DatatableElement">
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
  <xs:element name="TradableResourceDefinition" nillable="true" type="TradableResourceDefinition" />
  <xs:complexType name="TradableResourceDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="TradableDefinition">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="1" name="StartingQuantity" type="xs:string" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="TradableShipDefinition" nillable="true" type="TradableShipDefinition" />
  <xs:complexType name="TradableShipDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="TradableDefinition" />
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="TradableHeroDefinition" nillable="true" type="TradableHeroDefinition" />
  <xs:complexType name="TradableHeroDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="TradableDefinition" />
    </xs:complexContent>
  </xs:complexType>
</xs:schema>

=== AdrianLopezIglesias/EnhancedSpace-Adaptation/Simulation/TradableDefinitions[Heroes].xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Schemas/TradableDefinition.xsd">

    <!-- BasePrice must return a float. -->
    <!-- Vars: Marketplace (sim), SubCategory (sim), Level (int) -->

    <!-- Name is built as: 'TradableHero' + (Hero class name - 'HeroClass') -->
    <TradableHeroDefinition Name="TradableHeroAdmiral" Category="TradableCategoryHero" SubCategory="TradableSubCategoryHeroAdmiral">
      <BasePrice>150 + $(Level) * 850 + ( Property(Marketplace, Turn) * 65 )</BasePrice>
		  <SimulationDescriptorReference Name="TradableHeroAdmiral"/>
    </TradableHeroDefinition>

    <TradableHeroDefinition Name="TradableHeroAdministrator" Category="TradableCategoryHero" SubCategory="TradableSubCategoryHeroAdministrator">
      <BasePrice>150 + $(Level) * 850 + ( Property(Marketplace, Turn) * 65 )</BasePrice>
      <SimulationDescriptorReference Name="TradableHeroAdministrator"/>
    </TradableHeroDefinition>

    <TradableHeroDefinition Name="TradableHeroAdventurer" Category="TradableCategoryHero" SubCategory="TradableSubCategoryHeroAdventurer">
      <BasePrice>150 + $(Level) * 850 + ( Property(Marketplace, Turn) * 65 )</BasePrice>
      <SimulationDescriptorReference Name="TradableHeroAdventurer"/>
    </TradableHeroDefinition>

    <TradableHeroDefinition Name="TradableHeroCorporate" Category="TradableCategoryHero" SubCategory="TradableSubCategoryHeroCorporate">
      <BasePrice>150 + $(Level) * 850 + ( Property(Marketplace, Turn) * 65 )</BasePrice>
      <SimulationDescriptorReference Name="TradableHeroCorporate"/>
    </TradableHeroDefinition>
    
</Datatable>
